-- Running total of SpotScore generated by this post (camera creation + likes + first comments).
-- Mirrors the per-event increments applied to users.spot_score, so deleting a post can
-- cheaply reverse its contribution. GALLERY posts and posts capped by the daily limit stay at 0.
ALTER TABLE posts
    ADD COLUMN points INT NOT NULL DEFAULT 0;

ALTER TABLE posts
    ADD CONSTRAINT chk_post_points_non_negative CHECK (points >= 0);
