-- ============================================================
-- Car models reference data (seeded from cars.csv).
-- 2928 distinct (brand, model) pairs across 119 brands.
-- Brands stored in canonical display casing; models as-sourced.
-- Idempotent via ON CONFLICT against the UNIQUE (brand, model) constraint.
-- ============================================================

INSERT INTO car_models (brand, model) VALUES
    ('AC', 'Ace'),
    ('AC', 'Aceca'),
    ('AC', 'Cobra'),
    ('AC', 'Frua Convertible'),
    ('AC', 'Frua Coupe'),
    ('Acura', 'ADX'),
    ('Acura', 'CL'),
    ('Acura', 'CSX'),
    ('Acura', 'EL'),
    ('Acura', 'ILX'),
    ('Acura', 'Integra Coupe'),
    ('Acura', 'Integra Sedan'),
    ('Acura', 'Legend'),
    ('Acura', 'Legend Coupe'),
    ('Acura', 'MDX'),
    ('Acura', 'NSX'),
    ('Acura', 'RDX'),
    ('Acura', 'RL'),
    ('Acura', 'RLX'),
    ('Acura', 'RSX'),
    ('Acura', 'RSX TYPE-S'),
    ('Acura', 'SLX'),
    ('Acura', 'TL'),
    ('Acura', 'TLX'),
    ('Acura', 'TSX'),
    ('Acura', 'ZDX'),
    ('Alfa Romeo', '145'),
    ('Alfa Romeo', '146'),
    ('Alfa Romeo', '147 3 Doors'),
    ('Alfa Romeo', '147 5 Doors'),
    ('Alfa Romeo', '155'),
    ('Alfa Romeo', '156'),
    ('Alfa Romeo', '156 Sportwagon'),
    ('Alfa Romeo', '159'),
    ('Alfa Romeo', '159 Sportwagon'),
    ('Alfa Romeo', '164'),
    ('Alfa Romeo', '166'),
    ('Alfa Romeo', '1900'),
    ('Alfa Romeo', '2000'),
    ('Alfa Romeo', '24 HP'),
    ('Alfa Romeo', '2600'),
    ('Alfa Romeo', '33'),
    ('Alfa Romeo', '33 Sport Wagon'),
    ('Alfa Romeo', '4C'),
    ('Alfa Romeo', '4C Spider'),
    ('Alfa Romeo', '6'),
    ('Alfa Romeo', '6C'),
    ('Alfa Romeo', '75'),
    ('Alfa Romeo', '8C'),
    ('Alfa Romeo', 'Alfasud'),
    ('Alfa Romeo', 'Alfasud Giardinetta'),
    ('Alfa Romeo', 'Alfasud Sprint'),
    ('Alfa Romeo', 'Alfasud Ti'),
    ('Alfa Romeo', 'Alfetta'),
    ('Alfa Romeo', 'Arna'),
    ('Alfa Romeo', 'Brera'),
    ('Alfa Romeo', 'Crosswagon Q4'),
    ('Alfa Romeo', 'GT'),
    ('Alfa Romeo', 'GTV'),
    ('Alfa Romeo', 'Giulia'),
    ('Alfa Romeo', 'Giulia GTA'),
    ('Alfa Romeo', 'Giulia Quadrifoglio'),
    ('Alfa Romeo', 'Giulia Veloce'),
    ('Alfa Romeo', 'Giulietta'),
    ('Alfa Romeo', 'Giulietta Quadrifoglio Verde'),
    ('Alfa Romeo', 'Junior'),
    ('Alfa Romeo', 'MiTo'),
    ('Alfa Romeo', 'MiTo Quadrifoglio Verde'),
    ('Alfa Romeo', 'MiTo Veloce'),
    ('Alfa Romeo', 'Montreal'),
    ('Alfa Romeo', 'RL'),
    ('Alfa Romeo', 'RM'),
    ('Alfa Romeo', 'Spider'),
    ('Alfa Romeo', 'Sprint'),
    ('Alfa Romeo', 'Stelvio'),
    ('Alfa Romeo', 'Stelvio Quadrifoglio'),
    ('Alfa Romeo', 'Tipo 33'),
    ('Alfa Romeo', 'Tonale'),
    ('Alfa Romeo', 'Torpedo 20-30 HP'),
    ('Alpine', 'A106'),
    ('Alpine', 'A108'),
    ('Alpine', 'A110'),
    ('Alpine', 'A110S'),
    ('Alpine', 'A290'),
    ('Alpine', 'A390'),
    ('Arcfox', 'Alpha S'),
    ('Arcfox', 'Alpha T'),
    ('Ariel', 'Atom'),
    ('Ariel', 'Nomad'),
    ('Aro', '10 Series'),
    ('Aro', '24 Series'),
    ('Aro', 'IMS Series'),
    ('Aro', 'M Series'),
    ('Artega', 'GT'),
    ('Artega', 'Scalo'),
    ('Aston Martin', 'Cygnet'),
    ('Aston Martin', 'DB AR1'),
    ('Aston Martin', 'DB Mark III'),
    ('Aston Martin', 'DB11'),
    ('Aston Martin', 'DB11 Volante'),
    ('Aston Martin', 'DB12'),
    ('Aston Martin', 'DB12 Volante'),
    ('Aston Martin', 'DB2'),
    ('Aston Martin', 'DB4'),
    ('Aston Martin', 'DB5'),
    ('Aston Martin', 'DB6'),
    ('Aston Martin', 'DB6 Volante'),
    ('Aston Martin', 'DB7'),
    ('Aston Martin', 'DB7 Volante'),
    ('Aston Martin', 'DB9'),
    ('Aston Martin', 'DB9 Volante'),
    ('Aston Martin', 'DBS'),
    ('Aston Martin', 'DBS Volante'),
    ('Aston Martin', 'DBX'),
    ('Aston Martin', 'Lagonda'),
    ('Aston Martin', 'One-77'),
    ('Aston Martin', 'Rapide'),
    ('Aston Martin', 'Rapide AMR'),
    ('Aston Martin', 'Rapide E'),
    ('Aston Martin', 'Rapide S'),
    ('Aston Martin', 'V12 Speedster'),
    ('Aston Martin', 'V12 Vantage'),
    ('Aston Martin', 'V12 Vantage AMR'),
    ('Aston Martin', 'V12 Vantage S Roadster'),
    ('Aston Martin', 'V12 Zagato'),
    ('Aston Martin', 'V8 Vantage'),
    ('Aston Martin', 'V8 Vantage S'),
    ('Aston Martin', 'V8 Vantage S Roadster'),
    ('Aston Martin', 'V8 Volante'),
    ('Aston Martin', 'Valhalla'),
    ('Aston Martin', 'Vanquish'),
    ('Aston Martin', 'Vanquish S'),
    ('Aston Martin', 'Vanquish Volante'),
    ('Aston Martin', 'Vantage GT12'),
    ('Aston Martin', 'Vantage GT8'),
    ('Aston Martin', 'Vantage Roadster'),
    ('Aston Martin', 'Virage'),
    ('Aston Martin', 'Virage Volante'),
    ('Aston Martin', 'Vulcan'),
    ('Audi', '100 Coupe'),
    ('Audi', '100/ 200'),
    ('Audi', '100/ 200 Avant'),
    ('Audi', '80 Avant RS2'),
    ('Audi', '80 Avant S2'),
    ('Audi', '80 S2'),
    ('Audi', '80/ 90'),
    ('Audi', '80/ 90 Avant'),
    ('Audi', '90'),
    ('Audi', 'A1'),
    ('Audi', 'A1 Quattro'),
    ('Audi', 'A1 Sportback'),
    ('Audi', 'A2'),
    ('Audi', 'A3'),
    ('Audi', 'A3 Cabriolet'),
    ('Audi', 'A3 Sedan'),
    ('Audi', 'A3 Sportback'),
    ('Audi', 'A3 allstreet'),
    ('Audi', 'A4'),
    ('Audi', 'A4 Allroad'),
    ('Audi', 'A4 Avant'),
    ('Audi', 'A4 Cabriolet'),
    ('Audi', 'A4 DTM Edition'),
    ('Audi', 'A5 Avant'),
    ('Audi', 'A5 Cabriolet'),
    ('Audi', 'A5 Coupe'),
    ('Audi', 'A5 Sedan'),
    ('Audi', 'A5 Sportback'),
    ('Audi', 'A6'),
    ('Audi', 'A6 Avant'),
    ('Audi', 'A6 Sportback'),
    ('Audi', 'A7'),
    ('Audi', 'A8'),
    ('Audi', 'A8 (D2)'),
    ('Audi', 'Allroad'),
    ('Audi', 'Cabriolet'),
    ('Audi', 'Coupe'),
    ('Audi', 'Coupe S2'),
    ('Audi', 'E5 Sportback'),
    ('Audi', 'Q2'),
    ('Audi', 'Q3'),
    ('Audi', 'Q3 Sportback'),
    ('Audi', 'Q4 Sportback'),
    ('Audi', 'Q4 e-tron'),
    ('Audi', 'Q5'),
    ('Audi', 'Q5 Sportback'),
    ('Audi', 'Q6'),
    ('Audi', 'Q6 Sportback'),
    ('Audi', 'Q7'),
    ('Audi', 'Q8'),
    ('Audi', 'Q8 Sportback'),
    ('Audi', 'Q8 e-tron'),
    ('Audi', 'Quattro'),
    ('Audi', 'R8'),
    ('Audi', 'R8 GT'),
    ('Audi', 'R8 GT Spyder'),
    ('Audi', 'R8 Spyder'),
    ('Audi', 'RS 3 Sedan'),
    ('Audi', 'RS 3 Sportback'),
    ('Audi', 'RS 4'),
    ('Audi', 'RS 4 Avant'),
    ('Audi', 'RS 4 Cabriolet'),
    ('Audi', 'RS 5'),
    ('Audi', 'RS Q3'),
    ('Audi', 'RS Q8'),
    ('Audi', 'RS5 Avant'),
    ('Audi', 'RS5 Cabriolet'),
    ('Audi', 'RS5 Sedan'),
    ('Audi', 'RS5 Sportback'),
    ('Audi', 'RS6'),
    ('Audi', 'RS6 Avant'),
    ('Audi', 'RS7 Sportback'),
    ('Audi', 'S1'),
    ('Audi', 'S1 Sportback'),
    ('Audi', 'S3'),
    ('Audi', 'S3 Cabriolet'),
    ('Audi', 'S3 Sedan'),
    ('Audi', 'S3 Sportback'),
    ('Audi', 'S4'),
    ('Audi', 'S4 Avant'),
    ('Audi', 'S4 Cabriolet'),
    ('Audi', 'S5'),
    ('Audi', 'S5 Avant'),
    ('Audi', 'S5 Cabriolet'),
    ('Audi', 'S5 Sportback'),
    ('Audi', 'S6'),
    ('Audi', 'S6 Avant'),
    ('Audi', 'S7 Sportback'),
    ('Audi', 'S8'),
    ('Audi', 'S8 Plus'),
    ('Audi', 'SQ2'),
    ('Audi', 'SQ5'),
    ('Audi', 'SQ5 Sportback'),
    ('Audi', 'SQ6'),
    ('Audi', 'SQ6 Sportback'),
    ('Audi', 'SQ7'),
    ('Audi', 'SQ8'),
    ('Audi', 'SQ8 e-tron'),
    ('Audi', 'TT Coupe'),
    ('Audi', 'TT RS Coupe'),
    ('Audi', 'TT RS Roadster'),
    ('Audi', 'TT Roadster'),
    ('Audi', 'Typ R'),
    ('Audi', 'V8'),
    ('Audi', 'e-tron'),
    ('Audi', 'e-tron GT'),
    ('Audi', 'e-tron Sportback'),
    ('Aurus', 'Senat'),
    ('BAIC Motor', 'BJ60'),
    ('BMW', '1 Series'),
    ('BMW', '1 Series 3 doors'),
    ('BMW', '1 Series Cabriolet'),
    ('BMW', '1 Series Coupe'),
    ('BMW', '1 Series M Coupe'),
    ('BMW', '1 Series Sedan'),
    ('BMW', '1500/1600'),
    ('BMW', '2 Series Active Tourer'),
    ('BMW', '2 Series Convertible'),
    ('BMW', '2 Series Coupe'),
    ('BMW', '2 Series Gran Coupe'),
    ('BMW', '2 Series Gran Tourer'),
    ('BMW', '2000 CS'),
    ('BMW', '2002'),
    ('BMW', '2800 CS'),
    ('BMW', '3 Series Cabriolet'),
    ('BMW', '3 Series Compact'),
    ('BMW', '3 Series Coupe'),
    ('BMW', '3 Series Gran Turismo'),
    ('BMW', '3 Series Sedan'),
    ('BMW', '3 Series Touring'),
    ('BMW', '3.0 CSL'),
    ('BMW', '3.0 CSi'),
    ('BMW', '3/15 PS'),
    ('BMW', '3/20 PS'),
    ('BMW', '303'),
    ('BMW', '3200'),
    ('BMW', '326'),
    ('BMW', '327'),
    ('BMW', '328'),
    ('BMW', '335'),
    ('BMW', '4 Series Convertible'),
    ('BMW', '4 Series Coupe'),
    ('BMW', '4 Series Gran Coupe'),
    ('BMW', '5 Series Gran Turismo'),
    ('BMW', '5 Series Sedan'),
    ('BMW', '5 Series Touring'),
    ('BMW', '501/502'),
    ('BMW', '502 Coupe'),
    ('BMW', '503'),
    ('BMW', '507'),
    ('BMW', '6 Series Convertible'),
    ('BMW', '6 Series Coupe'),
    ('BMW', '6 Series Gran Coupe'),
    ('BMW', '6 Series Gran Turismo'),
    ('BMW', '7 Series'),
    ('BMW', '8 Series'),
    ('BMW', '8 Series Convertible'),
    ('BMW', '8 Series Coupe'),
    ('BMW', '8 Series Gran Coupe'),
    ('BMW', 'Isetta'),
    ('BMW', 'M1'),
    ('BMW', 'M2'),
    ('BMW', 'M2 CS'),
    ('BMW', 'M3 CS Touring'),
    ('BMW', 'M3 Cabriolet'),
    ('BMW', 'M3 Coupe'),
    ('BMW', 'M3 Sedan'),
    ('BMW', 'M3 Touring'),
    ('BMW', 'M4'),
    ('BMW', 'M4 CS'),
    ('BMW', 'M4 Convertible'),
    ('BMW', 'M4 GTS'),
    ('BMW', 'M5'),
    ('BMW', 'M5 Touring'),
    ('BMW', 'M6 Cabrio'),
    ('BMW', 'M6 Coupe'),
    ('BMW', 'M6 Gran Coupe'),
    ('BMW', 'M8 Convertible'),
    ('BMW', 'M8 Coupe'),
    ('BMW', 'M8 Gran Coupe'),
    ('BMW', 'X1'),
    ('BMW', 'X2'),
    ('BMW', 'X3'),
    ('BMW', 'X3 M'),
    ('BMW', 'X4'),
    ('BMW', 'X4 M'),
    ('BMW', 'X5'),
    ('BMW', 'X5 M'),
    ('BMW', 'X6'),
    ('BMW', 'X6 M'),
    ('BMW', 'X7'),
    ('BMW', 'XM'),
    ('BMW', 'Z1'),
    ('BMW', 'Z3 Coupe'),
    ('BMW', 'Z3 Roadster'),
    ('BMW', 'Z4 Coupe'),
    ('BMW', 'Z4 Roadster'),
    ('BMW', 'Z8'),
    ('BMW', 'i3'),
    ('BMW', 'i3 Sedan'),
    ('BMW', 'i4'),
    ('BMW', 'i5'),
    ('BMW', 'i5 Touring'),
    ('BMW', 'i7'),
    ('BMW', 'i8'),
    ('BMW', 'i8 Roadster'),
    ('BMW', 'iX'),
    ('BMW', 'iX M'),
    ('BMW', 'iX1'),
    ('BMW', 'iX2'),
    ('BMW', 'iX3'),
    ('BYD', 'ATTO 2'),
    ('BYD', 'ATTO 3'),
    ('BYD', 'DOLPHIN'),
    ('BYD', 'Sealion 7'),
    ('Bentley', 'Arnage'),
    ('Bentley', 'Azure'),
    ('Bentley', 'Batur Convertible'),
    ('Bentley', 'Bentayga'),
    ('Bentley', 'Bentayga Speed'),
    ('Bentley', 'Brooklands'),
    ('Bentley', 'Continental'),
    ('Bentley', 'Continental Flying Spur'),
    ('Bentley', 'Continental GT'),
    ('Bentley', 'Continental GTC'),
    ('Bentley', 'Flying Spur'),
    ('Bentley', 'Mk VI Saloon'),
    ('Bentley', 'Mulliner'),
    ('Bentley', 'Mulsanne'),
    ('Bentley', 'S1'),
    ('Bentley', 'State Limousine'),
    ('Bentley', 'T1'),
    ('Bentley', 'T2'),
    ('Borgward', 'BX7'),
    ('Bristol', '400'),
    ('Bristol', '402'),
    ('Bristol', '403'),
    ('Bristol', '404'),
    ('Bristol', '405'),
    ('Bristol', '406'),
    ('Bristol', '407'),
    ('Bristol', '408'),
    ('Bristol', '411'),
    ('Bristol', '412'),
    ('Bristol', '603'),
    ('Bristol', 'Blenheim'),
    ('Bristol', 'Bullet'),
    ('Bristol', 'Fighter'),
    ('Bristol', 'Series 6'),
    ('Bufori', 'CS8'),
    ('Bufori', 'Geneva'),
    ('Bufori', 'La Joya'),
    ('Bugatti', 'Bolide'),
    ('Bugatti', 'Brouillard'),
    ('Bugatti', 'Centodieci'),
    ('Bugatti', 'Chiron'),
    ('Bugatti', 'Divo'),
    ('Bugatti', 'EB 110'),
    ('Bugatti', 'La Voiture Noire'),
    ('Bugatti', 'Mistral'),
    ('Bugatti', 'Tourbillon'),
    ('Bugatti', 'Type 10'),
    ('Bugatti', 'Type 101'),
    ('Bugatti', 'Type 18'),
    ('Bugatti', 'Type 19'),
    ('Bugatti', 'Type 2'),
    ('Bugatti', 'Type 23'),
    ('Bugatti', 'Type 251'),
    ('Bugatti', 'Type 30'),
    ('Bugatti', 'Type 38'),
    ('Bugatti', 'Type 40'),
    ('Bugatti', 'Type 41'),
    ('Bugatti', 'Type 43'),
    ('Bugatti', 'Type 44'),
    ('Bugatti', 'Type 46'),
    ('Bugatti', 'Type 49'),
    ('Bugatti', 'Type 5'),
    ('Bugatti', 'Type 50'),
    ('Bugatti', 'Type 55'),
    ('Bugatti', 'Type 57'),
    ('Bugatti', 'Type 64'),
    ('Bugatti', 'Veyron'),
    ('Buick', 'Cascada'),
    ('Buick', 'Century'),
    ('Buick', 'Enclave'),
    ('Buick', 'Encore'),
    ('Buick', 'Envision'),
    ('Buick', 'Envista'),
    ('Buick', 'Gran Sport'),
    ('Buick', 'LaCrosse'),
    ('Buick', 'LeSabre'),
    ('Buick', 'Lucerne'),
    ('Buick', 'Model 21'),
    ('Buick', 'Model 26'),
    ('Buick', 'Model 27'),
    ('Buick', 'Model 32'),
    ('Buick', 'Model 33'),
    ('Buick', 'Model 38'),
    ('Buick', 'Model 39'),
    ('Buick', 'Model 41'),
    ('Buick', 'Model C'),
    ('Buick', 'Park Avenue'),
    ('Buick', 'Rainier'),
    ('Buick', 'Reatta'),
    ('Buick', 'Regal'),
    ('Buick', 'Regal Sportback'),
    ('Buick', 'Rendezvous'),
    ('Buick', 'Riviera'),
    ('Buick', 'Roadmaster'),
    ('Buick', 'Skylark'),
    ('Buick', 'Super Riviera'),
    ('Buick', 'Terraza'),
    ('Buick', 'Verano'),
    ('Cadillac', 'ATS'),
    ('Cadillac', 'ATS Coupe'),
    ('Cadillac', 'ATS-V'),
    ('Cadillac', 'ATS-V Coupe'),
    ('Cadillac', 'Allante'),
    ('Cadillac', 'BLS'),
    ('Cadillac', 'BLS Wagon'),
    ('Cadillac', 'Brougham'),
    ('Cadillac', 'CT4'),
    ('Cadillac', 'CT4-V'),
    ('Cadillac', 'CT5'),
    ('Cadillac', 'CT5-V'),
    ('Cadillac', 'CT6'),
    ('Cadillac', 'CTS'),
    ('Cadillac', 'CTS Coupe'),
    ('Cadillac', 'CTS Sport Wagon'),
    ('Cadillac', 'CTS V-Series'),
    ('Cadillac', 'CTS-V Coupe'),
    ('Cadillac', 'CTS-V Sport Wagon'),
    ('Cadillac', 'Catera'),
    ('Cadillac', 'Celestiq'),
    ('Cadillac', 'DTS'),
    ('Cadillac', 'DeVille'),
    ('Cadillac', 'ELR'),
    ('Cadillac', 'Eldorado'),
    ('Cadillac', 'Escalade'),
    ('Cadillac', 'Escalade ESV'),
    ('Cadillac', 'Escalade EXT'),
    ('Cadillac', 'Escalade IQL'),
    ('Cadillac', 'Lyriq'),
    ('Cadillac', 'Lyriq-V'),
    ('Cadillac', 'Optiq'),
    ('Cadillac', 'Optiq-V'),
    ('Cadillac', 'Runabout'),
    ('Cadillac', 'SRX'),
    ('Cadillac', 'STS'),
    ('Cadillac', 'Seville'),
    ('Cadillac', 'Vistiq'),
    ('Cadillac', 'XLR'),
    ('Cadillac', 'XLR V-Series'),
    ('Cadillac', 'XT4'),
    ('Cadillac', 'XT5'),
    ('Cadillac', 'XT6'),
    ('Cadillac', 'XTS'),
    ('Caterham', 'CSR'),
    ('Caterham', 'Classic'),
    ('Caterham', 'Roadsport'),
    ('Caterham', 'Seven 160')
ON CONFLICT (brand, model) DO NOTHING;

INSERT INTO car_models (brand, model) VALUES
    ('Caterham', 'Seven 620'),
    ('Caterham', 'Superlight'),
    ('Caterham', 'Supersport'),
    ('Caterham', 'The Super Seven 1600'),
    ('Chery', 'TIGGO 7'),
    ('Chery', 'TIGGO 8'),
    ('Chery', 'TIGGO 9'),
    ('Chevrolet', 'Agile'),
    ('Chevrolet', 'Astro'),
    ('Chevrolet', 'Avalanche'),
    ('Chevrolet', 'Aveo / Kalos 3 Doors'),
    ('Chevrolet', 'Aveo / Kalos 5 Doors'),
    ('Chevrolet', 'Aveo / Kalos Sedan'),
    ('Chevrolet', 'Blazer'),
    ('Chevrolet', 'Bolt'),
    ('Chevrolet', 'Camaro'),
    ('Chevrolet', 'Camaro Convertible'),
    ('Chevrolet', 'Captiva'),
    ('Chevrolet', 'Cavalier'),
    ('Chevrolet', 'Celta'),
    ('Chevrolet', 'Chevelle'),
    ('Chevrolet', 'Classic'),
    ('Chevrolet', 'Cobalt Coupe'),
    ('Chevrolet', 'Cobalt Sedan'),
    ('Chevrolet', 'Colorado Double Cab'),
    ('Chevrolet', 'Colorado Extended Cab'),
    ('Chevrolet', 'Colorado Regular Cab'),
    ('Chevrolet', 'Corvette Convertible'),
    ('Chevrolet', 'Corvette Coupe'),
    ('Chevrolet', 'Corvette E-Ray'),
    ('Chevrolet', 'Corvette Grand Sport'),
    ('Chevrolet', 'Corvette Grand Sport X'),
    ('Chevrolet', 'Corvette Z06'),
    ('Chevrolet', 'Corvette Z06 Convertible'),
    ('Chevrolet', 'Corvette ZR1'),
    ('Chevrolet', 'Corvette ZR1 Convertible'),
    ('Chevrolet', 'Cruze'),
    ('Chevrolet', 'Cruze - 5 doors'),
    ('Chevrolet', 'Cruze Wagon'),
    ('Chevrolet', 'Epica'),
    ('Chevrolet', 'Equinox'),
    ('Chevrolet', 'Evanda'),
    ('Chevrolet', 'Express'),
    ('Chevrolet', 'HHR'),
    ('Chevrolet', 'Impala'),
    ('Chevrolet', 'Impala Convertible'),
    ('Chevrolet', 'Impala Coupe'),
    ('Chevrolet', 'Malibu'),
    ('Chevrolet', 'Malibu Maxx'),
    ('Chevrolet', 'Matiz / Spark'),
    ('Chevrolet', 'Monte Carlo'),
    ('Chevrolet', 'Nomad'),
    ('Chevrolet', 'Nubira / Lacetti'),
    ('Chevrolet', 'Onix'),
    ('Chevrolet', 'Orlando'),
    ('Chevrolet', 'Prisma'),
    ('Chevrolet', 'S-10'),
    ('Chevrolet', 'SS'),
    ('Chevrolet', 'SSR'),
    ('Chevrolet', 'Silverado'),
    ('Chevrolet', 'Silverado 2500HD'),
    ('Chevrolet', 'Silverado 3500HD'),
    ('Chevrolet', 'Silverado Hybrid'),
    ('Chevrolet', 'Sonic Hatchback'),
    ('Chevrolet', 'Sonic RS'),
    ('Chevrolet', 'Sonic Sedan'),
    ('Chevrolet', 'Spark EV'),
    ('Chevrolet', 'Spin'),
    ('Chevrolet', 'Suburban'),
    ('Chevrolet', 'Tacuma'),
    ('Chevrolet', 'Tahoe'),
    ('Chevrolet', 'Tracker'),
    ('Chevrolet', 'TrailBlazer'),
    ('Chevrolet', 'Traverse'),
    ('Chevrolet', 'Trax'),
    ('Chevrolet', 'Uplander'),
    ('Chevrolet', 'Venture'),
    ('Chevrolet', 'Volt'),
    ('Chrysler', '200'),
    ('Chrysler', '200 Convertible'),
    ('Chrysler', '300'),
    ('Chrysler', '300 Sport Coupe'),
    ('Chrysler', '300C'),
    ('Chrysler', '300C Touring'),
    ('Chrysler', '300M'),
    ('Chrysler', 'Airflow'),
    ('Chrysler', 'Aspen'),
    ('Chrysler', 'Concorde'),
    ('Chrysler', 'Crossfire'),
    ('Chrysler', 'Crossfire Roadster'),
    ('Chrysler', 'Daytona'),
    ('Chrysler', 'Grand Voyager (AS)'),
    ('Chrysler', 'Imperial'),
    ('Chrysler', 'Imperial Roadster'),
    ('Chrysler', 'LeBaron'),
    ('Chrysler', 'New Yorker'),
    ('Chrysler', 'PT Cruiser'),
    ('Chrysler', 'PT Cruiser Convertible'),
    ('Chrysler', 'Pacifica'),
    ('Chrysler', 'Saratoga'),
    ('Chrysler', 'Sebring Convertible'),
    ('Chrysler', 'Sebring Coupe'),
    ('Chrysler', 'Sebring Sedan'),
    ('Chrysler', 'Six'),
    ('Chrysler', 'Town & Country'),
    ('Chrysler', 'Voyager'),
    ('Citroën', '2CV'),
    ('Citroën', 'AMI'),
    ('Citroën', 'AX 3 Doors'),
    ('Citroën', 'AX 5 Doors'),
    ('Citroën', 'Axel'),
    ('Citroën', 'BX'),
    ('Citroën', 'BX Break'),
    ('Citroën', 'Berlingo'),
    ('Citroën', 'C-Crosser'),
    ('Citroën', 'C-Elysee'),
    ('Citroën', 'C-Zero'),
    ('Citroën', 'C1 3 Doors'),
    ('Citroën', 'C1 5 Doors'),
    ('Citroën', 'C2'),
    ('Citroën', 'C3'),
    ('Citroën', 'C3 Aircross'),
    ('Citroën', 'C3 Picasso'),
    ('Citroën', 'C3 Pluriel'),
    ('Citroën', 'C4'),
    ('Citroën', 'C4 Aircross'),
    ('Citroën', 'C4 Cactus'),
    ('Citroën', 'C4 Coupe'),
    ('Citroën', 'C4 Hatchback'),
    ('Citroën', 'C4 Picasso'),
    ('Citroën', 'C4 Sedan'),
    ('Citroën', 'C5 Aircross'),
    ('Citroën', 'C5 Crosstourer'),
    ('Citroën', 'C5 Estate'),
    ('Citroën', 'C5 Liftback'),
    ('Citroën', 'C5 Sedan'),
    ('Citroën', 'C5 X'),
    ('Citroën', 'C6'),
    ('Citroën', 'C8'),
    ('Citroën', 'CX'),
    ('Citroën', 'CX Break'),
    ('Citroën', 'DS'),
    ('Citroën', 'DS3'),
    ('Citroën', 'DS4'),
    ('Citroën', 'DS5'),
    ('Citroën', 'Dyane'),
    ('Citroën', 'E-Mehari'),
    ('Citroën', 'Evasion'),
    ('Citroën', 'GSA'),
    ('Citroën', 'Grand C4 Picasso'),
    ('Citroën', 'LNA'),
    ('Citroën', 'Nemo'),
    ('Citroën', 'SM'),
    ('Citroën', 'Saxo 3 doors'),
    ('Citroën', 'Saxo 5 doors'),
    ('Citroën', 'Traction'),
    ('Citroën', 'Visa'),
    ('Citroën', 'Visa Decouvrable'),
    ('Citroën', 'XM'),
    ('Citroën', 'XM Break'),
    ('Citroën', 'Xantia'),
    ('Citroën', 'Xantia Break'),
    ('Citroën', 'Xsara'),
    ('Citroën', 'Xsara Break'),
    ('Citroën', 'Xsara Coupe'),
    ('Citroën', 'Xsara Picasso'),
    ('Citroën', 'ZX 3 Doors'),
    ('Citroën', 'ZX 5 Doors'),
    ('Citroën', 'ZX Break'),
    ('Cupra', 'Ateca'),
    ('Cupra', 'Born'),
    ('Cupra', 'Formentor'),
    ('Cupra', 'Leon'),
    ('Cupra', 'Leon Sportstourer'),
    ('Cupra', 'Raval'),
    ('Cupra', 'Tavascan'),
    ('Cupra', 'Terramar'),
    ('DR Motor', 'dr cityCROSS'),
    ('DR Motor', 'dr1'),
    ('DR Motor', 'dr2'),
    ('DR Motor', 'dr5'),
    ('DS Automobiles', 'DS 3'),
    ('DS Automobiles', 'DS 3 Cabrio'),
    ('DS Automobiles', 'DS 3 Crossback'),
    ('DS Automobiles', 'DS 4'),
    ('DS Automobiles', 'DS 5'),
    ('DS Automobiles', 'DS 5LS'),
    ('DS Automobiles', 'DS 7'),
    ('DS Automobiles', 'DS 9'),
    ('DS Automobiles', 'DS N8'),
    ('Dacia', '1100'),
    ('Dacia', '1300'),
    ('Dacia', '1300 Break'),
    ('Dacia', '1310'),
    ('Dacia', '1310 Break'),
    ('Dacia', '1310/1410 Sport'),
    ('Dacia', '1320'),
    ('Dacia', '1325'),
    ('Dacia', '500'),
    ('Dacia', 'Bigster'),
    ('Dacia', 'Dokker'),
    ('Dacia', 'Dokker Van'),
    ('Dacia', 'Duster'),
    ('Dacia', 'Duster Pick-Up'),
    ('Dacia', 'JOGGER'),
    ('Dacia', 'Lodgy'),
    ('Dacia', 'Logan'),
    ('Dacia', 'Logan MCV'),
    ('Dacia', 'Logan MCV Stepway'),
    ('Dacia', 'Logan Pick-Up'),
    ('Dacia', 'Logan Van'),
    ('Dacia', 'Nova'),
    ('Dacia', 'Sandero'),
    ('Dacia', 'Sandero Stepway'),
    ('Dacia', 'Solenza'),
    ('Dacia', 'Spring'),
    ('Dacia', 'Striker'),
    ('Dacia', 'SuperNova'),
    ('Daewoo', 'Cielo'),
    ('Daewoo', 'Cielo Hatchback 3 Doors'),
    ('Daewoo', 'Cielo Hatchback 5 Doors'),
    ('Daewoo', 'Damas II'),
    ('Daewoo', 'Espero'),
    ('Daewoo', 'G2X'),
    ('Daewoo', 'Gentra'),
    ('Daewoo', 'Lacetti'),
    ('Daewoo', 'Lacetti 5 doors'),
    ('Daewoo', 'Lacetti Wagon'),
    ('Daewoo', 'Lanos'),
    ('Daewoo', 'Lanos Hatchback 3 Doors'),
    ('Daewoo', 'Lanos Hatchback 5 Doors'),
    ('Daewoo', 'Leganza'),
    ('Daewoo', 'Magnus'),
    ('Daewoo', 'Matiz'),
    ('Daewoo', 'Nubira'),
    ('Daewoo', 'Nubira Estate'),
    ('Daewoo', 'Nubira Hatchback'),
    ('Daewoo', 'Statesman'),
    ('Daewoo', 'Tacuma'),
    ('Daewoo', 'Tico'),
    ('Daewoo', 'Tosca'),
    ('Daewoo', 'Winstorm'),
    ('Daihatsu', 'Altis'),
    ('Daihatsu', 'Applause'),
    ('Daihatsu', 'Ayla'),
    ('Daihatsu', 'Copen'),
    ('Daihatsu', 'Cuore'),
    ('Daihatsu', 'Feroza Hardtop'),
    ('Daihatsu', 'Feroza Softtop'),
    ('Daihatsu', 'Gran Move'),
    ('Daihatsu', 'Materia'),
    ('Daihatsu', 'Move'),
    ('Daihatsu', 'Rocky Hardtop'),
    ('Daihatsu', 'Rocky Wagon'),
    ('Daihatsu', 'Sirion'),
    ('Daihatsu', 'Sirion 2'),
    ('Daihatsu', 'Terios'),
    ('Daihatsu', 'Trevis'),
    ('Daihatsu', 'Valera'),
    ('Datsun', 'GO'),
    ('Datsun', 'GO+'),
    ('Datsun', 'Mi-Do'),
    ('Datsun', 'on-Do'),
    ('Dodge', 'Aries Coupe'),
    ('Dodge', 'Avenger'),
    ('Dodge', 'Caliber'),
    ('Dodge', 'Caliber SRT4'),
    ('Dodge', 'Caravan'),
    ('Dodge', 'Challenger'),
    ('Dodge', 'Challenger SRT'),
    ('Dodge', 'Charger'),
    ('Dodge', 'Charger SRT'),
    ('Dodge', 'Dakota'),
    ('Dodge', 'Dakota Club Cab'),
    ('Dodge', 'Dakota Quad Cab'),
    ('Dodge', 'Dart'),
    ('Dodge', 'Durango'),
    ('Dodge', 'Durango SRT'),
    ('Dodge', 'Hornet'),
    ('Dodge', 'Journey'),
    ('Dodge', 'Magnum'),
    ('Dodge', 'Magnum SRT8'),
    ('Dodge', 'Neon'),
    ('Dodge', 'Nitro'),
    ('Dodge', 'Polara'),
    ('Dodge', 'Ram'),
    ('Dodge', 'Stratus'),
    ('Dodge', 'Stratus Coupe'),
    ('Dodge', 'Viper'),
    ('Donkervoort', 'D8'),
    ('Donkervoort', 'P24'),
    ('Eagle', 'Premier'),
    ('Eagle', 'Summit'),
    ('Eagle', 'Summit Wagon'),
    ('Eagle', 'Talon'),
    ('FSO', '125'),
    ('FSO', 'Polonez'),
    ('FSO', 'Polonez Atu'),
    ('FSO', 'Polonez Caro'),
    ('FSO', 'Polonez Kombi'),
    ('FSO', 'Prima'),
    ('Ferrari', '125/159 S'),
    ('Ferrari', '12Cilindri'),
    ('Ferrari', '12Cilindri Spider'),
    ('Ferrari', '166 Spider Corsa'),
    ('Ferrari', '166 Sport'),
    ('Ferrari', '195'),
    ('Ferrari', '212'),
    ('Ferrari', '250'),
    ('Ferrari', '275'),
    ('Ferrari', '288 GTO/F40/F50/Enzo/LaFerrari'),
    ('Ferrari', '296 GTB'),
    ('Ferrari', '296 GTS'),
    ('Ferrari', '296 Speciale'),
    ('Ferrari', '308 GTB/GTS'),
    ('Ferrari', '328 GTB/GTS'),
    ('Ferrari', '348'),
    ('Ferrari', '348 Spider'),
    ('Ferrari', '360 Challenge Stradale'),
    ('Ferrari', '360 Modena'),
    ('Ferrari', '360 Spider'),
    ('Ferrari', '365'),
    ('Ferrari', '365GT4 BB/ 512BB/ 512 BBi'),
    ('Ferrari', '400'),
    ('Ferrari', '456 GT'),
    ('Ferrari', '458 Italia'),
    ('Ferrari', '458 Speciale'),
    ('Ferrari', '458 Speciale A'),
    ('Ferrari', '458 Spider'),
    ('Ferrari', '488 GTB'),
    ('Ferrari', '488 Pista'),
    ('Ferrari', '488 Spider'),
    ('Ferrari', '550 Barchetta/575M Superamerica'),
    ('Ferrari', '550/575M Maranello'),
    ('Ferrari', '599'),
    ('Ferrari', '612 Scaglietti'),
    ('Ferrari', '812'),
    ('Ferrari', 'Amalfi'),
    ('Ferrari', 'Amalfi Spider'),
    ('Ferrari', 'California T'),
    ('Ferrari', 'Daytona'),
    ('Ferrari', 'Dino'),
    ('Ferrari', 'F12 Berlinetta'),
    ('Ferrari', 'F12 TRS'),
    ('Ferrari', 'F12tdf'),
    ('Ferrari', 'F149 California'),
    ('Ferrari', 'F355'),
    ('Ferrari', 'F355 Spider'),
    ('Ferrari', 'F430'),
    ('Ferrari', 'F430 Spider'),
    ('Ferrari', 'F60 America'),
    ('Ferrari', 'F8'),
    ('Ferrari', 'F80'),
    ('Ferrari', 'FF'),
    ('Ferrari', 'FXX'),
    ('Ferrari', 'GTC4Lusso'),
    ('Ferrari', 'GTC4Lusso T'),
    ('Ferrari', 'LaFerrari'),
    ('Ferrari', 'Mondial'),
    ('Ferrari', 'Mondial Cabriolet'),
    ('Ferrari', 'Monza'),
    ('Ferrari', 'Portofino'),
    ('Ferrari', 'Purosangue'),
    ('Ferrari', 'Roma'),
    ('Ferrari', 'Roma Convertible'),
    ('Ferrari', 'SF90'),
    ('Ferrari', 'Scuderia Spider'),
    ('Ferrari', 'Testarossa Spider'),
    ('Ferrari', 'Testarossa/512 TR/512M'),
    ('Fiat', '1100 D'),
    ('Fiat', '1100 D Station Wagon'),
    ('Fiat', '1100 E'),
    ('Fiat', '1100 S'),
    ('Fiat', '1100 TV Spider'),
    ('Fiat', '12 HP'),
    ('Fiat', '12-15 HP Zero'),
    ('Fiat', '1200'),
    ('Fiat', '1200 Spider'),
    ('Fiat', '124 Coupe'),
    ('Fiat', '124 Familiale'),
    ('Fiat', '124 Saloon'),
    ('Fiat', '124 Spider'),
    ('Fiat', '125'),
    ('Fiat', '126'),
    ('Fiat', '127'),
    ('Fiat', '127 Panorama'),
    ('Fiat', '128 Coupe'),
    ('Fiat', '128 Saloon'),
    ('Fiat', '130 Coupe'),
    ('Fiat', '130 Limousine'),
    ('Fiat', '131 4 doors'),
    ('Fiat', '132'),
    ('Fiat', '1400'),
    ('Fiat', '1400 Cabriolet'),
    ('Fiat', '15-25 HP Brevetti Tipo 2'),
    ('Fiat', '1500'),
    ('Fiat', '16-20 HP'),
    ('Fiat', '1800 / 2100'),
    ('Fiat', '2300 Coupe'),
    ('Fiat', '2300 Saloon'),
    ('Fiat', '2300 Station Wagon'),
    ('Fiat', '2800'),
    ('Fiat', '3 1/2 HP'),
    ('Fiat', '500'),
    ('Fiat', '500 3+1'),
    ('Fiat', '500 Abarth'),
    ('Fiat', '500 K / Giardiniera'),
    ('Fiat', '500L'),
    ('Fiat', '500L Living'),
    ('Fiat', '500L Trekking'),
    ('Fiat', '500L Urban'),
    ('Fiat', '500X'),
    ('Fiat', '500e'),
    ('Fiat', '501'),
    ('Fiat', '501 S'),
    ('Fiat', '502'),
    ('Fiat', '503 Torpedo'),
    ('Fiat', '505'),
    ('Fiat', '507'),
    ('Fiat', '507 Touring'),
    ('Fiat', '509'),
    ('Fiat', '509 S'),
    ('Fiat', '514'),
    ('Fiat', '514 Spider'),
    ('Fiat', '519 Berlina'),
    ('Fiat', '519 Coupe'),
    ('Fiat', '519 S'),
    ('Fiat', '520 Superfiat'),
    ('Fiat', '521'),
    ('Fiat', '522 C'),
    ('Fiat', '524 C'),
    ('Fiat', '525'),
    ('Fiat', '527'),
    ('Fiat', '600'),
    ('Fiat', '600 D'),
    ('Fiat', '600 Multipla'),
    ('Fiat', '850'),
    ('Fiat', '850 Coupe'),
    ('Fiat', '850 Spider'),
    ('Fiat', '8V'),
    ('Fiat', 'Albea / Siena'),
    ('Fiat', 'Argenta'),
    ('Fiat', 'Argo'),
    ('Fiat', 'Barchetta'),
    ('Fiat', 'Brava'),
    ('Fiat', 'Bravo'),
    ('Fiat', 'Brevetti'),
    ('Fiat', 'Campagnola'),
    ('Fiat', 'Cinquecento'),
    ('Fiat', 'Coupe'),
    ('Fiat', 'Croma'),
    ('Fiat', 'Dino Coupe'),
    ('Fiat', 'Dino Spider'),
    ('Fiat', 'Doblo'),
    ('Fiat', 'Freemont'),
    ('Fiat', 'Fullback'),
    ('Fiat', 'Grande Panda'),
    ('Fiat', 'Grande Punto / Punto Evo 3 Doors'),
    ('Fiat', 'Grande Punto / Punto Evo 5 Doors'),
    ('Fiat', 'Idea'),
    ('Fiat', 'Linea'),
    ('Fiat', 'Marea'),
    ('Fiat', 'Marea Weekend'),
    ('Fiat', 'Mille'),
    ('Fiat', 'Multipla'),
    ('Fiat', 'Palio'),
    ('Fiat', 'Palio Weekend'),
    ('Fiat', 'Panda'),
    ('Fiat', 'Panda 4X4'),
    ('Fiat', 'Panda City Cross'),
    ('Fiat', 'Panda Cross'),
    ('Fiat', 'Punto 3 Doors'),
    ('Fiat', 'Punto 5 Doors'),
    ('Fiat', 'Punto Cabrio'),
    ('Fiat', 'Qubo'),
    ('Fiat', 'Regata'),
    ('Fiat', 'Regata Weekend'),
    ('Fiat', 'Ritmo'),
    ('Fiat', 'Sedici'),
    ('Fiat', 'Seicento'),
    ('Fiat', 'Stilo 3 Doors'),
    ('Fiat', 'Stilo 5 Doors'),
    ('Fiat', 'Stilo Multi Wagon'),
    ('Fiat', 'Tempra'),
    ('Fiat', 'Tempra SW'),
    ('Fiat', 'Tipo'),
    ('Fiat', 'Tipo 3 Doors'),
    ('Fiat', 'Tipo 5 Doors'),
    ('Fiat', 'Tipo Cross'),
    ('Fiat', 'Tipo Station Wagon'),
    ('Fiat', 'Topolino'),
    ('Fiat', 'Ulysse'),
    ('Fiat', 'Uno'),
    ('Fiat', 'Uno 3 Doors'),
    ('Fiat', 'Uno 5 Doors'),
    ('Fiat', 'Viaggio'),
    ('Fiat', 'X1/9'),
    ('Fisker', 'Karma'),
    ('Fisker', 'Ocean'),
    ('Ford', 'Anglia 100E')
ON CONFLICT (brand, model) DO NOTHING;

INSERT INTO car_models (brand, model) VALUES
    ('Ford', 'Anglia 105E'),
    ('Ford', 'B-Max'),
    ('Ford', 'Bronco'),
    ('Ford', 'C-Max'),
    ('Ford', 'Capri'),
    ('Ford', 'Capri SUV'),
    ('Ford', 'Consul'),
    ('Ford', 'Contour/Mondeo'),
    ('Ford', 'Corsair'),
    ('Ford', 'Cortina'),
    ('Ford', 'Cougar'),
    ('Ford', 'Crestline'),
    ('Ford', 'Crestliner'),
    ('Ford', 'Crown Victoria'),
    ('Ford', 'Deluxe'),
    ('Ford', 'E-Tourneo'),
    ('Ford', 'EcoSport'),
    ('Ford', 'Econovan'),
    ('Ford', 'Edge'),
    ('Ford', 'Edge ST'),
    ('Ford', 'Escape'),
    ('Ford', 'Escort 3 Doors'),
    ('Ford', 'Escort 4 Doors'),
    ('Ford', 'Escort 5 Doors'),
    ('Ford', 'Escort Cabrio'),
    ('Ford', 'Escort Clipper'),
    ('Ford', 'Escort Wagon'),
    ('Ford', 'Everest'),
    ('Ford', 'Excursion'),
    ('Ford', 'Expedition'),
    ('Ford', 'Explorer'),
    ('Ford', 'Explorer Electric'),
    ('Ford', 'Explorer Sport'),
    ('Ford', 'Explorer Sport Trac'),
    ('Ford', 'F-150 Raptor'),
    ('Ford', 'F-150 Regular Cab'),
    ('Ford', 'F-150 Super Cab'),
    ('Ford', 'F-150 Super Crew'),
    ('Ford', 'Fiesta 3 Doors'),
    ('Ford', 'Fiesta 5 Doors'),
    ('Ford', 'Fiesta ST'),
    ('Ford', 'Fiesta Sedan'),
    ('Ford', 'Figo'),
    ('Ford', 'Five Hundred'),
    ('Ford', 'Flex'),
    ('Ford', 'Focus 3 Doors'),
    ('Ford', 'Focus 5 Doors'),
    ('Ford', 'Focus CC'),
    ('Ford', 'Focus RS'),
    ('Ford', 'Focus ST 5 doors'),
    ('Ford', 'Focus ST Wagon'),
    ('Ford', 'Focus Sedan'),
    ('Ford', 'Focus US'),
    ('Ford', 'Focus Wagon'),
    ('Ford', 'Freestar'),
    ('Ford', 'Freestyle'),
    ('Ford', 'Fusion European'),
    ('Ford', 'Fusion North American'),
    ('Ford', 'GT'),
    ('Ford', 'Galaxy'),
    ('Ford', 'Grand C-MAX'),
    ('Ford', 'Ka'),
    ('Ford', 'Ka+'),
    ('Ford', 'Ka+ Active'),
    ('Ford', 'Kuga'),
    ('Ford', 'Maverick'),
    ('Ford', 'Maverick LWB'),
    ('Ford', 'Maverick SWB'),
    ('Ford', 'Model A'),
    ('Ford', 'Model T'),
    ('Ford', 'Mondeo Hatchback'),
    ('Ford', 'Mondeo Sedan'),
    ('Ford', 'Mondeo Wagon'),
    ('Ford', 'Mustang'),
    ('Ford', 'Mustang Convertible'),
    ('Ford', 'Mustang MACH-E'),
    ('Ford', 'Mustang Mach 1'),
    ('Ford', 'Orion'),
    ('Ford', 'Pinto'),
    ('Ford', 'Probe'),
    ('Ford', 'Puma'),
    ('Ford', 'Puma ST'),
    ('Ford', 'Ranger Double Cab'),
    ('Ford', 'Ranger Regular Cab'),
    ('Ford', 'Ranger Super Cab'),
    ('Ford', 'Ranger Tremor'),
    ('Ford', 'Ranger Wildtrak'),
    ('Ford', 'Raptor Ranger'),
    ('Ford', 'S-Max'),
    ('Ford', 'Scorpio Sedan'),
    ('Ford', 'Scorpio Wagon'),
    ('Ford', 'Sierra 3 Doors'),
    ('Ford', 'Sierra 5 Doors'),
    ('Ford', 'Sierra Sedan'),
    ('Ford', 'SportKa'),
    ('Ford', 'StreetKa'),
    ('Ford', 'Super Duty'),
    ('Ford', 'Taunus'),
    ('Ford', 'Taunus Cabrio'),
    ('Ford', 'Taurus'),
    ('Ford', 'Taurus SHO'),
    ('Ford', 'Taurus Wagon'),
    ('Ford', 'Taurus X'),
    ('Ford', 'Territory'),
    ('Ford', 'Thunderbird'),
    ('Ford', 'Tourneo'),
    ('Ford', 'Transit Connect Wagon'),
    ('Ford', 'Transit Custom'),
    ('Ford', 'Wildtrak'),
    ('Ford', 'Windstar'),
    ('Ford', 'Zodiac'),
    ('GMC', 'Acadia'),
    ('GMC', 'Canyon Crew Cab'),
    ('GMC', 'Canyon Double Cab'),
    ('GMC', 'Canyon Regular Cab'),
    ('GMC', 'Envoy'),
    ('GMC', 'Envoy XL'),
    ('GMC', 'Envoy XUV'),
    ('GMC', 'Hummer EV'),
    ('GMC', 'Hummer EV SUV'),
    ('GMC', 'Jimmy 3 Doors'),
    ('GMC', 'Jimmy 5 Doors'),
    ('GMC', 'Safari'),
    ('GMC', 'Savana'),
    ('GMC', 'Sierra'),
    ('GMC', 'Sierra 2500HD'),
    ('GMC', 'Sierra 3500HD'),
    ('GMC', 'Terrain'),
    ('GMC', 'Typhoon'),
    ('GMC', 'Yukon'),
    ('GMC', 'Yukon XL'),
    ('Geely', 'CK'),
    ('Geely', 'Emgrand EC7'),
    ('Geely', 'Galaxy'),
    ('Geely', 'Galaxy M9'),
    ('Geely', 'LC'),
    ('Geely', 'MK'),
    ('Genesis', 'G70'),
    ('Genesis', 'G70 Shooting Brake'),
    ('Genesis', 'G80'),
    ('Genesis', 'G90'),
    ('Genesis', 'GV60'),
    ('Genesis', 'GV70'),
    ('Genesis', 'GV80'),
    ('Genesis', 'GV80 Coupe'),
    ('Hindustan', 'Ambassador'),
    ('Hindustan', 'Pushpak/Trekker'),
    ('Hindustan', 'RTV/Ranger'),
    ('Holden', '48-215'),
    ('Holden', 'Adventra'),
    ('Holden', 'Astra 3 Doors'),
    ('Holden', 'Astra 5 Doors'),
    ('Holden', 'Astra Caravan'),
    ('Holden', 'Astra TwinTop'),
    ('Holden', 'Barina 3 Doors'),
    ('Holden', 'Barina 5 Doors'),
    ('Holden', 'Barina RS'),
    ('Holden', 'Barina Sedan'),
    ('Holden', 'Barina Spark'),
    ('Holden', 'Caprice/Statesman'),
    ('Holden', 'Captiva'),
    ('Holden', 'Captiva MaXX'),
    ('Holden', 'Combo'),
    ('Holden', 'Commodore Sedan'),
    ('Holden', 'Commodore Wagon'),
    ('Holden', 'Crewman'),
    ('Holden', 'Cruze Mk I'),
    ('Holden', 'Cruze Mk II'),
    ('Holden', 'Drover'),
    ('Holden', 'Drover Deluxe'),
    ('Holden', 'EJ Wagon'),
    ('Holden', 'Epica'),
    ('Holden', 'FE'),
    ('Holden', 'FJ'),
    ('Holden', 'Frontera MX'),
    ('Holden', 'HJ'),
    ('Holden', 'HZ'),
    ('Holden', 'Jackaroo'),
    ('Holden', 'Malibu'),
    ('Holden', 'Monaro'),
    ('Holden', 'Rodeo'),
    ('Holden', 'Statesman'),
    ('Holden', 'Tigra'),
    ('Holden', 'Trax'),
    ('Holden', 'Ute'),
    ('Holden', 'Vectra Liftback'),
    ('Holden', 'Vectra Sedan'),
    ('Holden', 'Zafira'),
    ('Honda', '1300 Coupe'),
    ('Honda', '1300 Sedan'),
    ('Honda', 'Accord'),
    ('Honda', 'Accord 3 Doors'),
    ('Honda', 'Accord Coupe'),
    ('Honda', 'Accord Crosstour'),
    ('Honda', 'Accord Euro'),
    ('Honda', 'Accord Tourer'),
    ('Honda', 'Accord Type R'),
    ('Honda', 'Airwave'),
    ('Honda', 'Avancier'),
    ('Honda', 'Beat'),
    ('Honda', 'CR-V'),
    ('Honda', 'CR-Z'),
    ('Honda', 'CRX Del Sol'),
    ('Honda', 'Civic 3 Doors'),
    ('Honda', 'Civic 5 Doors'),
    ('Honda', 'Civic Aero Deck'),
    ('Honda', 'Civic CRX'),
    ('Honda', 'Civic Coupe'),
    ('Honda', 'Civic Sedan'),
    ('Honda', 'Civic Sedan US'),
    ('Honda', 'Civic Shuttle'),
    ('Honda', 'Civic Si Sedan US'),
    ('Honda', 'Civic Tourer'),
    ('Honda', 'Civic Type-R'),
    ('Honda', 'Clarity'),
    ('Honda', 'Concerto'),
    ('Honda', 'Element'),
    ('Honda', 'FR-V / Edix'),
    ('Honda', 'Fit EV'),
    ('Honda', 'HR-V 3 Doors'),
    ('Honda', 'HR-V 5 Doors'),
    ('Honda', 'Insight'),
    ('Honda', 'Jazz / City'),
    ('Honda', 'Jazz / Fit'),
    ('Honda', 'L700'),
    ('Honda', 'Legend Coupe'),
    ('Honda', 'Legend Sedan'),
    ('Honda', 'Logo / Fit'),
    ('Honda', 'MDX'),
    ('Honda', 'Mobilio'),
    ('Honda', 'N360'),
    ('Honda', 'N600'),
    ('Honda', 'NSX'),
    ('Honda', 'Odyssey'),
    ('Honda', 'Passport'),
    ('Honda', 'Pilot'),
    ('Honda', 'Prelude'),
    ('Honda', 'Prologue'),
    ('Honda', 'Ridgeline'),
    ('Honda', 'S2000'),
    ('Honda', 'S500'),
    ('Honda', 'S600'),
    ('Honda', 'S660'),
    ('Honda', 'S800'),
    ('Honda', 'S800C'),
    ('Honda', 'Shuttle'),
    ('Honda', 'Stream'),
    ('Honda', 'That''s'),
    ('Honda', 'ZR-V'),
    ('Honda', 'e'),
    ('Honda', 'e:Ny1'),
    ('Hummer', 'H1 2 Door Hardtop'),
    ('Hummer', 'H1 4 Door Hardtop'),
    ('Hummer', 'H1 4 Door Opentop'),
    ('Hummer', 'H1 4 Door Wagon'),
    ('Hummer', 'H2'),
    ('Hummer', 'H2 SUT'),
    ('Hummer', 'H3'),
    ('Hummer', 'H3 Alpha'),
    ('Hyundai', 'Accent 3 Doors'),
    ('Hyundai', 'Accent 5 Doors'),
    ('Hyundai', 'Accent Sedan'),
    ('Hyundai', 'Atos'),
    ('Hyundai', 'Atos Multi'),
    ('Hyundai', 'Atos Spirit'),
    ('Hyundai', 'Bayon'),
    ('Hyundai', 'Coupe / Tiburon'),
    ('Hyundai', 'Elantra 5 Doors'),
    ('Hyundai', 'Elantra Coupe'),
    ('Hyundai', 'Elantra GT'),
    ('Hyundai', 'Elantra N'),
    ('Hyundai', 'Elantra Sedan'),
    ('Hyundai', 'Elantra Touring'),
    ('Hyundai', 'Equus'),
    ('Hyundai', 'Excel 3 Doors'),
    ('Hyundai', 'Excel 5 Doors'),
    ('Hyundai', 'Excel Sedan'),
    ('Hyundai', 'Genesis'),
    ('Hyundai', 'Genesis Coupe'),
    ('Hyundai', 'Getz 3 Doors'),
    ('Hyundai', 'Getz 5 Doors'),
    ('Hyundai', 'Grandeur / Azera'),
    ('Hyundai', 'Ioniq'),
    ('Hyundai', 'Ioniq 3'),
    ('Hyundai', 'Ioniq 5'),
    ('Hyundai', 'Ioniq 6'),
    ('Hyundai', 'Ioniq 9'),
    ('Hyundai', 'Kona'),
    ('Hyundai', 'Kona Electric'),
    ('Hyundai', 'Kona N'),
    ('Hyundai', 'Lantra'),
    ('Hyundai', 'Lantra Wagon'),
    ('Hyundai', 'Matrix'),
    ('Hyundai', 'Mistra'),
    ('Hyundai', 'NEXO'),
    ('Hyundai', 'Palisade'),
    ('Hyundai', 'Pony 3 Doors'),
    ('Hyundai', 'Pony 5 Doors'),
    ('Hyundai', 'Santa Cruz'),
    ('Hyundai', 'Santa Fe'),
    ('Hyundai', 'Satellite'),
    ('Hyundai', 'Scoupe'),
    ('Hyundai', 'Sonata'),
    ('Hyundai', 'Sonata Hybrid'),
    ('Hyundai', 'Staria'),
    ('Hyundai', 'Terracan'),
    ('Hyundai', 'Trajet'),
    ('Hyundai', 'Veloster'),
    ('Hyundai', 'Venue'),
    ('Hyundai', 'XG'),
    ('Hyundai', 'i10'),
    ('Hyundai', 'i20'),
    ('Hyundai', 'i20 Active'),
    ('Hyundai', 'i20 Coupe'),
    ('Hyundai', 'i20 N'),
    ('Hyundai', 'i30'),
    ('Hyundai', 'i30 Coupe'),
    ('Hyundai', 'i30 Estate'),
    ('Hyundai', 'i30 Fastback'),
    ('Hyundai', 'i30 N'),
    ('Hyundai', 'i40'),
    ('Hyundai', 'i40 wagon'),
    ('Hyundai', 'i800 / H-1'),
    ('Hyundai', 'ix20'),
    ('Hyundai', 'ix35 / Tucson'),
    ('Hyundai', 'ix55 / Veracruz'),
    ('Ineos', 'Grenadier'),
    ('Infiniti', 'EX'),
    ('Infiniti', 'FX'),
    ('Infiniti', 'G Convertible'),
    ('Infiniti', 'G Coupe'),
    ('Infiniti', 'G Sedan'),
    ('Infiniti', 'G20'),
    ('Infiniti', 'G35'),
    ('Infiniti', 'G35 Coupe'),
    ('Infiniti', 'I'),
    ('Infiniti', 'J'),
    ('Infiniti', 'JX'),
    ('Infiniti', 'M Convertible'),
    ('Infiniti', 'M Coupe'),
    ('Infiniti', 'M Sedan'),
    ('Infiniti', 'Q'),
    ('Infiniti', 'Q40'),
    ('Infiniti', 'Q50'),
    ('Infiniti', 'Q60'),
    ('Infiniti', 'Q60 Convertible'),
    ('Infiniti', 'Q70'),
    ('Infiniti', 'QX'),
    ('Infiniti', 'QX30'),
    ('Infiniti', 'QX50'),
    ('Infiniti', 'QX55'),
    ('Infiniti', 'QX60'),
    ('Infiniti', 'QX65'),
    ('Infiniti', 'QX70'),
    ('Infiniti', 'QX80'),
    ('Isuzu', '117 Coupe'),
    ('Isuzu', 'Amigo 3 Doors'),
    ('Isuzu', 'Amigo Cabrio'),
    ('Isuzu', 'Ascender'),
    ('Isuzu', 'Axiom'),
    ('Isuzu', 'Hombre Crew Cab'),
    ('Isuzu', 'MU-7'),
    ('Isuzu', 'Rodeo / D-Max'),
    ('Isuzu', 'Trooper 3 Doors'),
    ('Isuzu', 'Trooper 5 Doors'),
    ('Isuzu', 'i-Series'),
    ('Jaguar', 'E-Pace'),
    ('Jaguar', 'F-Pace'),
    ('Jaguar', 'F-Pace SVR'),
    ('Jaguar', 'F-Type Convertible'),
    ('Jaguar', 'F-Type Coupe'),
    ('Jaguar', 'F-Type SVR'),
    ('Jaguar', 'F-Type SVR Coupe'),
    ('Jaguar', 'I-Pace'),
    ('Jaguar', 'S-Type'),
    ('Jaguar', 'S-Type R'),
    ('Jaguar', 'X-Type'),
    ('Jaguar', 'X-Type Estate'),
    ('Jaguar', 'XE'),
    ('Jaguar', 'XE SV'),
    ('Jaguar', 'XF'),
    ('Jaguar', 'XF Sportbrake'),
    ('Jaguar', 'XFR'),
    ('Jaguar', 'XJ'),
    ('Jaguar', 'XJ220'),
    ('Jaguar', 'XJR'),
    ('Jaguar', 'XK'),
    ('Jaguar', 'XK Convertible'),
    ('Jaguar', 'XKR'),
    ('Jaguar', 'XKR Convertible'),
    ('Jeep', 'Avenger'),
    ('Jeep', 'Cherokee'),
    ('Jeep', 'Cherokee/Liberty'),
    ('Jeep', 'Commander'),
    ('Jeep', 'Compass'),
    ('Jeep', 'Gladiator'),
    ('Jeep', 'Grand Cherokee'),
    ('Jeep', 'Patriot'),
    ('Jeep', 'Recon'),
    ('Jeep', 'Renegade'),
    ('Jeep', 'Wagoneer'),
    ('Jeep', 'Wrangler'),
    ('Jeep', 'Wrangler Rubicon'),
    ('Jeep', 'Wrangler Unlimited'),
    ('KTM', 'X-Bow'),
    ('Kia', 'Borrego / Mohave'),
    ('Kia', 'Carens'),
    ('Kia', 'Carnival / Sedona'),
    ('Kia', 'Ceed'),
    ('Kia', 'Cerato / Spectra'),
    ('Kia', 'Cerato/Forte'),
    ('Kia', 'EV2'),
    ('Kia', 'EV3'),
    ('Kia', 'EV4'),
    ('Kia', 'EV4 Hatchback'),
    ('Kia', 'EV5'),
    ('Kia', 'EV6'),
    ('Kia', 'EV9'),
    ('Kia', 'Forte'),
    ('Kia', 'Forte 5 Door'),
    ('Kia', 'Forte Koup'),
    ('Kia', 'Joice'),
    ('Kia', 'K4'),
    ('Kia', 'K4 Hatchback'),
    ('Kia', 'K5'),
    ('Kia', 'K7 / Cadenza'),
    ('Kia', 'K9'),
    ('Kia', 'Niro'),
    ('Kia', 'Opirus / Amanti'),
    ('Kia', 'Optima / Magentis'),
    ('Kia', 'Optima Sportswagon'),
    ('Kia', 'Picanto'),
    ('Kia', 'Picanto X-Line'),
    ('Kia', 'Pro cee''d'),
    ('Kia', 'Rio Hatchback'),
    ('Kia', 'Rio Sedan'),
    ('Kia', 'Rondo'),
    ('Kia', 'Seltos'),
    ('Kia', 'Shuma'),
    ('Kia', 'Sorento'),
    ('Kia', 'Soul'),
    ('Kia', 'Sportage'),
    ('Kia', 'Stinger'),
    ('Kia', 'Stonic'),
    ('Kia', 'Stonic GT-Line'),
    ('Kia', 'Syros'),
    ('Kia', 'Tasman'),
    ('Kia', 'Telluride'),
    ('Kia', 'Venga'),
    ('Kia', 'XCeed'),
    ('Kia', 'cee''d'),
    ('Kia', 'cee''d SW'),
    ('Kia', 'pro_cee’d GT'),
    ('Koenigsegg', 'Agera'),
    ('Koenigsegg', 'CC8S'),
    ('Koenigsegg', 'CCR'),
    ('Koenigsegg', 'CCX'),
    ('Koenigsegg', 'CCXR'),
    ('Koenigsegg', 'Gemera'),
    ('Koenigsegg', 'Jesko'),
    ('Koenigsegg', 'One:1'),
    ('Koenigsegg', 'Regera'),
    ('Koenigsegg', 'Sadairs Spear'),
    ('Lada', '110'),
    ('Lada', '111'),
    ('Lada', '112'),
    ('Lada', 'Kalina Hatchback'),
    ('Lada', 'Kalina Sedan'),
    ('Lada', 'Niva'),
    ('Lada', 'Nova'),
    ('Lada', 'Nova Combi'),
    ('Lada', 'Priora'),
    ('Lada', 'Samara 3 Doors'),
    ('Lada', 'Samara 5 Doors'),
    ('Lada', 'Samara Sedan'),
    ('Lamborghini', '350 GT/ 400 GT'),
    ('Lamborghini', '350 GTS'),
    ('Lamborghini', 'Aventador'),
    ('Lamborghini', 'Aventador Roadster'),
    ('Lamborghini', 'Centenario'),
    ('Lamborghini', 'Centenario Roadster'),
    ('Lamborghini', 'Countach'),
    ('Lamborghini', 'Diablo'),
    ('Lamborghini', 'Diablo Roadster'),
    ('Lamborghini', 'Espada'),
    ('Lamborghini', 'Gallardo'),
    ('Lamborghini', 'Gallardo Spyder'),
    ('Lamborghini', 'Huracan'),
    ('Lamborghini', 'Huracan Spyder'),
    ('Lamborghini', 'Islero'),
    ('Lamborghini', 'Jalpa'),
    ('Lamborghini', 'Jarama'),
    ('Lamborghini', 'LM 002'),
    ('Lamborghini', 'Miura'),
    ('Lamborghini', 'Murcielago'),
    ('Lamborghini', 'Murcielago Roadster'),
    ('Lamborghini', 'Reventon'),
    ('Lamborghini', 'Revuelto'),
    ('Lamborghini', 'Sian'),
    ('Lamborghini', 'Sian Roadster')
ON CONFLICT (brand, model) DO NOTHING;

INSERT INTO car_models (brand, model) VALUES
    ('Lamborghini', 'Silhouette'),
    ('Lamborghini', 'Temerario'),
    ('Lamborghini', 'Urraco'),
    ('Lamborghini', 'Urus'),
    ('Lamborghini', 'Veneno'),
    ('Lamborghini', 'Veneno Roadster'),
    ('Lancia', '2000 Coupe'),
    ('Lancia', 'A112'),
    ('Lancia', 'A112 Abarth'),
    ('Lancia', 'Alpha'),
    ('Lancia', 'Aprilia'),
    ('Lancia', 'Ardea'),
    ('Lancia', 'Artena'),
    ('Lancia', 'Astura'),
    ('Lancia', 'Augusta'),
    ('Lancia', 'Beta'),
    ('Lancia', 'Beta Coupe'),
    ('Lancia', 'Beta Montecarlo'),
    ('Lancia', 'Beta Spider'),
    ('Lancia', 'Dedra'),
    ('Lancia', 'Dedra Station Wagon'),
    ('Lancia', 'Delta'),
    ('Lancia', 'Delta HPE'),
    ('Lancia', 'Dilambda'),
    ('Lancia', 'Flaminia Coupe'),
    ('Lancia', 'Flaminia Sedan'),
    ('Lancia', 'Flavia Convertible'),
    ('Lancia', 'Flavia Sedan'),
    ('Lancia', 'Fulvia Berlina'),
    ('Lancia', 'Fulvia Coupe'),
    ('Lancia', 'Gamma'),
    ('Lancia', 'Gamma Coupe'),
    ('Lancia', 'Kappa'),
    ('Lancia', 'Kappa Coupe'),
    ('Lancia', 'Kappa SW'),
    ('Lancia', 'Lambda'),
    ('Lancia', 'Lybra'),
    ('Lancia', 'Lybra SW'),
    ('Lancia', 'Musa'),
    ('Lancia', 'Phedra'),
    ('Lancia', 'Prisma'),
    ('Lancia', 'Stratos'),
    ('Lancia', 'Thema'),
    ('Lancia', 'Thesis'),
    ('Lancia', 'Theta'),
    ('Lancia', 'Trevi'),
    ('Lancia', 'Voyager'),
    ('Lancia', 'Ypsilon'),
    ('Lancia', 'Zeta'),
    ('Land Rover', 'Defender 110'),
    ('Land Rover', 'Defender 130'),
    ('Land Rover', 'Defender 90'),
    ('Land Rover', 'Defender Octa'),
    ('Land Rover', 'Discovery'),
    ('Land Rover', 'Discovery SVX'),
    ('Land Rover', 'Discovery Sport'),
    ('Land Rover', 'Freelander'),
    ('Land Rover', 'Range Rover'),
    ('Land Rover', 'Range Rover 3 Doors'),
    ('Land Rover', 'Range Rover Evoque'),
    ('Land Rover', 'Range Rover Evoque Convertible'),
    ('Land Rover', 'Range Rover L'),
    ('Land Rover', 'Range Rover PHEV'),
    ('Land Rover', 'Range Rover Sport'),
    ('Land Rover', 'Range Rover Sport PHEV'),
    ('Land Rover', 'Range Rover Sport SVR'),
    ('Land Rover', 'Range Rover Velar'),
    ('Lexus', 'CT'),
    ('Lexus', 'ES'),
    ('Lexus', 'GS'),
    ('Lexus', 'GS F'),
    ('Lexus', 'GX'),
    ('Lexus', 'HS'),
    ('Lexus', 'IS'),
    ('Lexus', 'LBX'),
    ('Lexus', 'LC'),
    ('Lexus', 'LFA'),
    ('Lexus', 'LM'),
    ('Lexus', 'LS'),
    ('Lexus', 'LX'),
    ('Lexus', 'NX'),
    ('Lexus', 'RC'),
    ('Lexus', 'RC F'),
    ('Lexus', 'RX'),
    ('Lexus', 'RZ'),
    ('Lexus', 'SC'),
    ('Lexus', 'TX'),
    ('Lexus', 'UX'),
    ('Lightyear', 'Lightyear 0'),
    ('Lightyear', 'Lightyear 2'),
    ('Lincoln', 'Aviator'),
    ('Lincoln', 'Continental'),
    ('Lincoln', 'Corsair'),
    ('Lincoln', 'LS'),
    ('Lincoln', 'MKC'),
    ('Lincoln', 'MKS'),
    ('Lincoln', 'MKT'),
    ('Lincoln', 'MKX'),
    ('Lincoln', 'MKZ'),
    ('Lincoln', 'Mark LT'),
    ('Lincoln', 'Nautilus'),
    ('Lincoln', 'Navigator'),
    ('Lincoln', 'Navigator L'),
    ('Lincoln', 'Town Car'),
    ('Lincoln', 'Zephyr'),
    ('Lincoln', 'Zephyr Fastback'),
    ('Lotus', '2 Eleven'),
    ('Lotus', '3 Eleven'),
    ('Lotus', 'Elan'),
    ('Lotus', 'Eletre'),
    ('Lotus', 'Elise'),
    ('Lotus', 'Elite'),
    ('Lotus', 'Emeya'),
    ('Lotus', 'Emira'),
    ('Lotus', 'Esprit'),
    ('Lotus', 'Europa'),
    ('Lotus', 'Evija'),
    ('Lotus', 'Evora'),
    ('Lotus', 'Excel'),
    ('Lotus', 'Exige'),
    ('MG', 'F/ TF'),
    ('MG', 'GS'),
    ('MG', 'HS'),
    ('MG', 'IM5'),
    ('MG', 'IM6'),
    ('MG', 'MG 3'),
    ('MG', 'MG 4'),
    ('MG', 'MG 5'),
    ('MG', 'MG 6'),
    ('MG', 'Marvel R'),
    ('MG', 'S5 EV'),
    ('MG', 'U9'),
    ('MG', 'XPower'),
    ('MG', 'ZR 3 Doors'),
    ('MG', 'ZR 5 Doors'),
    ('MG', 'ZS'),
    ('MG', 'ZS Hatchback'),
    ('MG', 'ZS Sedan'),
    ('MG', 'ZT'),
    ('MG', 'ZT-T'),
    ('MINI', 'Aceman'),
    ('MINI', 'Classic'),
    ('MINI', 'Clubman'),
    ('MINI', 'Clubvan'),
    ('MINI', 'Convertible'),
    ('MINI', 'Countryman'),
    ('MINI', 'Coupe'),
    ('MINI', 'Hatch'),
    ('MINI', 'Paceman'),
    ('MINI', 'Roadster'),
    ('Marussia', 'B1'),
    ('Marussia', 'B2'),
    ('Maruti Suzuki', '800'),
    ('Maruti Suzuki', 'Alto'),
    ('Maruti Suzuki', 'Baleno'),
    ('Maruti Suzuki', 'Ciaz'),
    ('Maruti Suzuki', 'Esteem'),
    ('Maruti Suzuki', 'Gipsy'),
    ('Maruti Suzuki', 'Swift'),
    ('Maruti Suzuki', 'Wagon R'),
    ('Maruti Suzuki', 'Zen'),
    ('Maserati', 'Bora'),
    ('Maserati', 'Coupe'),
    ('Maserati', 'GT2 Stradale'),
    ('Maserati', 'Ghibli'),
    ('Maserati', 'GranCabrio'),
    ('Maserati', 'GranSport'),
    ('Maserati', 'GranTurismo'),
    ('Maserati', 'Grecale'),
    ('Maserati', 'Grecale Trofeo'),
    ('Maserati', 'Indy'),
    ('Maserati', 'Levante'),
    ('Maserati', 'MC 12'),
    ('Maserati', 'MC20'),
    ('Maserati', 'MCPura'),
    ('Maserati', 'MCPura Cielo'),
    ('Maserati', 'Merak'),
    ('Maserati', 'Quattroporte'),
    ('Maserati', 'Quattroporte Sport GT S'),
    ('Maserati', 'Spyder'),
    ('Maybach', '57'),
    ('Maybach', '62'),
    ('Maybach', 'Landaulet'),
    ('Maybach', 'Typ 12'),
    ('Maybach', 'Typ SW 35, SW 38 and SW 42'),
    ('Maybach', 'Typ W1, W2, W3, W5 and W5 SG'),
    ('Maybach', 'Typ W6, W6 DSG and DSH'),
    ('Maybach', 'Typ Zeppelin'),
    ('Mazda', '121'),
    ('Mazda', '2 / Demio'),
    ('Mazda', '2 / Demio - 3 doors'),
    ('Mazda', '2 / Demio - Sedan'),
    ('Mazda', '3 / Axela Hatchback'),
    ('Mazda', '3 / Axela Sedan'),
    ('Mazda', '3 MPS / MAZDASPEED 3'),
    ('Mazda', '323 Hatchback'),
    ('Mazda', '323 Sedan'),
    ('Mazda', '323 Station Wagon'),
    ('Mazda', '5 / Premacy'),
    ('Mazda', '6 / Atenza Hatchback'),
    ('Mazda', '6 / Atenza Sedan'),
    ('Mazda', '6 / Atenza Wagon'),
    ('Mazda', '626 Hatchback'),
    ('Mazda', '626 Sedan'),
    ('Mazda', '626 Station Wagon'),
    ('Mazda', '6e'),
    ('Mazda', 'B Series / Bravo Dual Cab'),
    ('Mazda', 'B Series / Bravo Freestyle Cab'),
    ('Mazda', 'BT-50'),
    ('Mazda', 'Biante'),
    ('Mazda', 'CX-3'),
    ('Mazda', 'CX-30'),
    ('Mazda', 'CX-5'),
    ('Mazda', 'CX-50'),
    ('Mazda', 'CX-60'),
    ('Mazda', 'CX-6e'),
    ('Mazda', 'CX-7'),
    ('Mazda', 'CX-70'),
    ('Mazda', 'CX-8'),
    ('Mazda', 'CX-80'),
    ('Mazda', 'CX-9'),
    ('Mazda', 'CX-90'),
    ('Mazda', 'Flair'),
    ('Mazda', 'Flairwagon'),
    ('Mazda', 'MX-3'),
    ('Mazda', 'MX-30'),
    ('Mazda', 'MX-5 / Miata'),
    ('Mazda', 'MX-6'),
    ('Mazda', 'RX-7'),
    ('Mazda', 'RX-8'),
    ('Mazda', 'Tribute'),
    ('Mazda', 'Verisa'),
    ('Mazda', 'Xedos 6'),
    ('Mazda', 'Xedos 9'),
    ('McLaren', '12C GT Sprint'),
    ('McLaren', '540C'),
    ('McLaren', '570GT'),
    ('McLaren', '570S'),
    ('McLaren', '570S Spider'),
    ('McLaren', '600LT'),
    ('McLaren', '620R'),
    ('McLaren', '650S'),
    ('McLaren', '650S Spider'),
    ('McLaren', '675LT'),
    ('McLaren', '675LT Spider'),
    ('McLaren', '720S'),
    ('McLaren', '750S'),
    ('McLaren', '765LT'),
    ('McLaren', 'Artura'),
    ('McLaren', 'Elva'),
    ('McLaren', 'F1'),
    ('McLaren', 'F1 GT'),
    ('McLaren', 'F1 LM'),
    ('McLaren', 'GT'),
    ('McLaren', 'GTS'),
    ('McLaren', 'MP4-12C'),
    ('McLaren', 'MP4-12C Spider'),
    ('McLaren', 'P1'),
    ('McLaren', 'Senna'),
    ('McLaren', 'Speedtail'),
    ('Mercedes-Benz', 'A-Class Sedan'),
    ('Mercedes-Benz', 'A-Klasse'),
    ('Mercedes-Benz', 'A-Klasse AMG'),
    ('Mercedes-Benz', 'A-Klasse Coupe'),
    ('Mercedes-Benz', 'A-Klasse Saloon'),
    ('Mercedes-Benz', 'B-Klasse'),
    ('Mercedes-Benz', 'C-Class Cabriolet'),
    ('Mercedes-Benz', 'C-Class EV'),
    ('Mercedes-Benz', 'C-Klasse AMG'),
    ('Mercedes-Benz', 'C-Klasse All-Terrain'),
    ('Mercedes-Benz', 'C-Klasse Coupe'),
    ('Mercedes-Benz', 'C-Klasse Coupe AMG'),
    ('Mercedes-Benz', 'C-Klasse SportCoupe AMG'),
    ('Mercedes-Benz', 'C-Klasse SportCoupe/CLC'),
    ('Mercedes-Benz', 'C-Klasse T-Modell'),
    ('Mercedes-Benz', 'C-Klasse T-Modell AMG'),
    ('Mercedes-Benz', 'C-Klasse and predecessors'),
    ('Mercedes-Benz', 'CL AMG'),
    ('Mercedes-Benz', 'CL-Klasse and predecessors'),
    ('Mercedes-Benz', 'CLA 45'),
    ('Mercedes-Benz', 'CLA Klasse'),
    ('Mercedes-Benz', 'CLA Shooting Brake'),
    ('Mercedes-Benz', 'CLE Cabriolet'),
    ('Mercedes-Benz', 'CLE Coupe'),
    ('Mercedes-Benz', 'CLK AMG'),
    ('Mercedes-Benz', 'CLK AMG Cabrio'),
    ('Mercedes-Benz', 'CLK GTR'),
    ('Mercedes-Benz', 'CLS AMG'),
    ('Mercedes-Benz', 'CLS Shooting Brake'),
    ('Mercedes-Benz', 'CLS Shooting Brake AMG'),
    ('Mercedes-Benz', 'CLS-Klasse'),
    ('Mercedes-Benz', 'Citan'),
    ('Mercedes-Benz', 'E-Class T-Modell All-Terrain'),
    ('Mercedes-Benz', 'E-Klasse AMG'),
    ('Mercedes-Benz', 'E-Klasse Cabriolet and predecessors'),
    ('Mercedes-Benz', 'E-Klasse Coupe and predecessors'),
    ('Mercedes-Benz', 'E-Klasse T-Modell'),
    ('Mercedes-Benz', 'E-Klasse T-Modell AMG'),
    ('Mercedes-Benz', 'E-Klasse and predecessors'),
    ('Mercedes-Benz', 'EQA'),
    ('Mercedes-Benz', 'EQB'),
    ('Mercedes-Benz', 'EQC'),
    ('Mercedes-Benz', 'EQE'),
    ('Mercedes-Benz', 'EQE SUV'),
    ('Mercedes-Benz', 'EQS'),
    ('Mercedes-Benz', 'EQS SUV'),
    ('Mercedes-Benz', 'EQS SUV Maybach'),
    ('Mercedes-Benz', 'EQT'),
    ('Mercedes-Benz', 'EQV'),
    ('Mercedes-Benz', 'G-Klasse'),
    ('Mercedes-Benz', 'G-Klasse AMG'),
    ('Mercedes-Benz', 'G-Klasse Cabriolet'),
    ('Mercedes-Benz', 'G-Klasse Kurz'),
    ('Mercedes-Benz', 'G1, G4, G5, L 1500 A, 170 VL, 170 VK'),
    ('Mercedes-Benz', 'GL-Klasse'),
    ('Mercedes-Benz', 'GL-Klasse AMG'),
    ('Mercedes-Benz', 'GLA'),
    ('Mercedes-Benz', 'GLB'),
    ('Mercedes-Benz', 'GLC Class'),
    ('Mercedes-Benz', 'GLC Class Coupe'),
    ('Mercedes-Benz', 'GLE-Class'),
    ('Mercedes-Benz', 'GLE-Class Coupe'),
    ('Mercedes-Benz', 'GLK-Klasse'),
    ('Mercedes-Benz', 'GLS Maybach'),
    ('Mercedes-Benz', 'GLS-Class'),
    ('Mercedes-Benz', 'Laundalet'),
    ('Mercedes-Benz', 'M-Klasse'),
    ('Mercedes-Benz', 'M-Klasse AMG'),
    ('Mercedes-Benz', 'Maybach EQS SUV'),
    ('Mercedes-Benz', 'Pullman'),
    ('Mercedes-Benz', 'R-Klasse'),
    ('Mercedes-Benz', 'R-Klasse AMG'),
    ('Mercedes-Benz', 'R-Klasse Lang'),
    ('Mercedes-Benz', 'S-Class Cabriolet'),
    ('Mercedes-Benz', 'S-Class Coupe AMG'),
    ('Mercedes-Benz', 'S-Class Maybach'),
    ('Mercedes-Benz', 'S-Klasse AMG'),
    ('Mercedes-Benz', 'S-Klasse Coupe'),
    ('Mercedes-Benz', 'S-Klasse and predecessors'),
    ('Mercedes-Benz', 'SL AMG'),
    ('Mercedes-Benz', 'SL Monogram Maybach'),
    ('Mercedes-Benz', 'SL-Klasse'),
    ('Mercedes-Benz', 'SLC-Class'),
    ('Mercedes-Benz', 'SLK AMG'),
    ('Mercedes-Benz', 'SLK-Klasse'),
    ('Mercedes-Benz', 'SLR McLaren'),
    ('Mercedes-Benz', 'SLS AMG'),
    ('Mercedes-Benz', 'T-Class'),
    ('Mercedes-Benz', 'Typ 12/55 - 14/60'),
    ('Mercedes-Benz', 'Typ 130, 150 and 170 H'),
    ('Mercedes-Benz', 'Typ 170/170 V'),
    ('Mercedes-Benz', 'Typ 200'),
    ('Mercedes-Benz', 'Typ 230, 260 D'),
    ('Mercedes-Benz', 'Typ 290'),
    ('Mercedes-Benz', 'Typ 320'),
    ('Mercedes-Benz', 'Typ 380'),
    ('Mercedes-Benz', 'Typ 500 K/ 540 K'),
    ('Mercedes-Benz', 'Typ 770'),
    ('Mercedes-Benz', 'Typ 8/38'),
    ('Mercedes-Benz', 'Typ Mannheim'),
    ('Mercedes-Benz', 'Typ Nurburg'),
    ('Mercedes-Benz', 'Typ S, SS, SSK, SSKL'),
    ('Mercedes-Benz', 'Typ Stuttgart'),
    ('Mercedes-Benz', 'V-Class and predecessors'),
    ('Mercedes-Benz', 'VANEO'),
    ('Mercedes-Benz', 'VIANO'),
    ('Mercedes-Benz', 'VLE'),
    ('Mercedes-Benz', 'Vito'),
    ('Mercedes-Benz', 'X-Class'),
    ('Mercury', 'Cougar'),
    ('Mercury', 'Grand Marquis'),
    ('Mercury', 'Marauder'),
    ('Mercury', 'Mariner'),
    ('Mercury', 'Milan'),
    ('Mercury', 'Montego'),
    ('Mercury', 'Monterey'),
    ('Mercury', 'Mountaineer'),
    ('Mercury', 'Sable'),
    ('Mercury', 'Villager'),
    ('Mitsubishi', '3000 GT'),
    ('Mitsubishi', 'ASX / RVR / Outlander Sport'),
    ('Mitsubishi', 'Attrage'),
    ('Mitsubishi', 'Carisma Sedan'),
    ('Mitsubishi', 'Colt 3 Doors'),
    ('Mitsubishi', 'Colt 5 Doors'),
    ('Mitsubishi', 'Colt CZC'),
    ('Mitsubishi', 'Eclipse'),
    ('Mitsubishi', 'Eclipse Cross'),
    ('Mitsubishi', 'Eclipse Spyder'),
    ('Mitsubishi', 'Endeavor'),
    ('Mitsubishi', 'Galant'),
    ('Mitsubishi', 'Galant Station Wagon'),
    ('Mitsubishi', 'Grandis'),
    ('Mitsubishi', 'L 200'),
    ('Mitsubishi', 'L300'),
    ('Mitsubishi', 'Lancer'),
    ('Mitsubishi', 'Lancer Combi'),
    ('Mitsubishi', 'Lancer Evolution'),
    ('Mitsubishi', 'Lancer Hatchback'),
    ('Mitsubishi', 'Mirage'),
    ('Mitsubishi', 'Mirage G4'),
    ('Mitsubishi', 'Outlander / Airtrek'),
    ('Mitsubishi', 'Pajero 3 Doors'),
    ('Mitsubishi', 'Pajero 5 Doors'),
    ('Mitsubishi', 'Pajero Pinin / Shogun Pinin / Montero iO'),
    ('Mitsubishi', 'Raider Crew Cab'),
    ('Mitsubishi', 'Raider Double Cab'),
    ('Mitsubishi', 'Sigma'),
    ('Mitsubishi', 'Space Runner'),
    ('Mitsubishi', 'Space Star'),
    ('Mitsubishi', 'Starion'),
    ('Mitsubishi', 'i-MiEV'),
    ('Morgan', '3 wheeler'),
    ('Morgan', '4/4 2 Seater'),
    ('Morgan', '4/4 4 Seater'),
    ('Morgan', 'Aero 8'),
    ('Morgan', 'Aero Coupe'),
    ('Morgan', 'Aero SuperSports'),
    ('Morgan', 'AeroMax'),
    ('Morgan', 'Plus 4'),
    ('Morgan', 'Plus 8'),
    ('Morgan', 'Plus Six'),
    ('Morgan', 'Roadster'),
    ('NIO', 'EC6'),
    ('NIO', 'EP9'),
    ('NIO', 'ES6'),
    ('NIO', 'ES8'),
    ('NIO', 'ET7'),
    ('Nissan', '100 NX'),
    ('Nissan', '200 SX'),
    ('Nissan', '300 ZX'),
    ('Nissan', '350Z'),
    ('Nissan', '350Z Roadster'),
    ('Nissan', '370Z'),
    ('Nissan', '370Z Nismo'),
    ('Nissan', '370Z Roadster'),
    ('Nissan', 'Almera / Pulsar 3 Doors'),
    ('Nissan', 'Almera / Pulsar 5 Doors'),
    ('Nissan', 'Almera / Pulsar Sedan'),
    ('Nissan', 'Almera Tino'),
    ('Nissan', 'Altima'),
    ('Nissan', 'Ariya'),
    ('Nissan', 'Armada'),
    ('Nissan', 'Bluebird Hatchback'),
    ('Nissan', 'Bluebird Sedan'),
    ('Nissan', 'Bluebird Traveller'),
    ('Nissan', 'Cube'),
    ('Nissan', 'Elgrand'),
    ('Nissan', 'GT-R'),
    ('Nissan', 'GT-R Nismo'),
    ('Nissan', 'Grand Livina'),
    ('Nissan', 'Juke'),
    ('Nissan', 'Juke EV'),
    ('Nissan', 'Juke Nismo'),
    ('Nissan', 'Kicks'),
    ('Nissan', 'Leaf'),
    ('Nissan', 'Liberty'),
    ('Nissan', 'Maxima'),
    ('Nissan', 'Micra 3 Doors'),
    ('Nissan', 'Micra 5 Doors'),
    ('Nissan', 'Micra C+C'),
    ('Nissan', 'Murano'),
    ('Nissan', 'Murano CrossCabriolet'),
    ('Nissan', 'N7'),
    ('Nissan', 'NP300'),
    ('Nissan', 'NV'),
    ('Nissan', 'Navara / Frontier Double Cab'),
    ('Nissan', 'Navara / Frontier King Cab'),
    ('Nissan', 'Note'),
    ('Nissan', 'Pathfinder'),
    ('Nissan', 'Patrol LWB'),
    ('Nissan', 'Patrol SWB'),
    ('Nissan', 'Pixo'),
    ('Nissan', 'Platina'),
    ('Nissan', 'Prairie'),
    ('Nissan', 'Primera Break'),
    ('Nissan', 'Primera Hatchback'),
    ('Nissan', 'Primera Sedan'),
    ('Nissan', 'Qashqai'),
    ('Nissan', 'Quest'),
    ('Nissan', 'Rogue'),
    ('Nissan', 'Sakura'),
    ('Nissan', 'Sentra'),
    ('Nissan', 'Serena'),
    ('Nissan', 'Skyline'),
    ('Nissan', 'Sunny'),
    ('Nissan', 'Sunny 3 Doors'),
    ('Nissan', 'Sunny Hatchback'),
    ('Nissan', 'Sunny Sedan'),
    ('Nissan', 'Sunny Traveller'),
    ('Nissan', 'Teana'),
    ('Nissan', 'Terrano 3 Doors'),
    ('Nissan', 'Terrano 5 Doors'),
    ('Nissan', 'Tiida / Versa'),
    ('Nissan', 'Tiida / Versa Sedan'),
    ('Nissan', 'Titan Crew Cab'),
    ('Nissan', 'Titan King Cab'),
    ('Nissan', 'X-Trail'),
    ('Nissan', 'XTerra'),
    ('Nissan', 'Z Nismo')
ON CONFLICT (brand, model) DO NOTHING;

INSERT INTO car_models (brand, model) VALUES
    ('Oldsmobile', '442 Convertible'),
    ('Oldsmobile', '88'),
    ('Oldsmobile', 'Alero coupe'),
    ('Oldsmobile', 'Alero sedan'),
    ('Oldsmobile', 'Aurora'),
    ('Oldsmobile', 'Bravada'),
    ('Oldsmobile', 'Curved Dash'),
    ('Oldsmobile', 'Cutlass'),
    ('Oldsmobile', 'Intrigue'),
    ('Oldsmobile', 'Silhouette'),
    ('Oldsmobile', 'Toronado'),
    ('Opel', 'Adam'),
    ('Opel', 'Adam Rocks'),
    ('Opel', 'Agila'),
    ('Opel', 'Ampera'),
    ('Opel', 'Antara'),
    ('Opel', 'Astra 3 Doors'),
    ('Opel', 'Astra 5 Doors'),
    ('Opel', 'Astra Cabriolet'),
    ('Opel', 'Astra Caravan'),
    ('Opel', 'Astra Coupe'),
    ('Opel', 'Astra GTC'),
    ('Opel', 'Astra OPC'),
    ('Opel', 'Astra Sedan'),
    ('Opel', 'Astra Sports Tourer'),
    ('Opel', 'Astra Twin Top / Cabriolet'),
    ('Opel', 'Calibra'),
    ('Opel', 'Cascada'),
    ('Opel', 'Combo'),
    ('Opel', 'Corsa 3 Doors'),
    ('Opel', 'Corsa 5 Doors'),
    ('Opel', 'Corsa OPC'),
    ('Opel', 'Crossland'),
    ('Opel', 'Frontera'),
    ('Opel', 'GT'),
    ('Opel', 'Grandland'),
    ('Opel', 'Insignia'),
    ('Opel', 'Insignia Country Tourer'),
    ('Opel', 'Insignia GSi'),
    ('Opel', 'Insignia OPC'),
    ('Opel', 'Insignia Sports Tourer'),
    ('Opel', 'Insignia Sports Tourer GSi'),
    ('Opel', 'Insignia Sports Tourer OPC'),
    ('Opel', 'Kadett 3 Doors'),
    ('Opel', 'Kadett 5 Doors'),
    ('Opel', 'Kadett Cabriolet'),
    ('Opel', 'Kadett Caravan'),
    ('Opel', 'Kadett Sedan'),
    ('Opel', 'Karl'),
    ('Opel', 'Manta'),
    ('Opel', 'Meriva'),
    ('Opel', 'Mokka'),
    ('Opel', 'Monterey'),
    ('Opel', 'Monza'),
    ('Opel', 'Omega Caravan'),
    ('Opel', 'Omega Sedan'),
    ('Opel', 'Rekord Caravan'),
    ('Opel', 'Rekord Sedan'),
    ('Opel', 'Rocks-e'),
    ('Opel', 'Senator'),
    ('Opel', 'Signum'),
    ('Opel', 'Sintra'),
    ('Opel', 'Speedster'),
    ('Opel', 'Tigra'),
    ('Opel', 'Vectra Caravan'),
    ('Opel', 'Vectra Hatchback'),
    ('Opel', 'Vectra OPC'),
    ('Opel', 'Vectra Sedan'),
    ('Opel', 'Zafira'),
    ('Pagani', 'Huayra'),
    ('Pagani', 'Huayra Roadster'),
    ('Pagani', 'Imola'),
    ('Pagani', 'Utopia'),
    ('Pagani', 'Zonda Cinque'),
    ('Pagani', 'Zonda Cinque Roadster'),
    ('Pagani', 'Zonda F'),
    ('Pagani', 'Zonda F Roadster'),
    ('Pagani', 'Zonda Roadster'),
    ('Pagani', 'Zonda S'),
    ('Panoz', 'Avezzano'),
    ('Panoz', 'Esperante'),
    ('Panoz', 'Esperante GT'),
    ('Panoz', 'Esperante GTLM'),
    ('Panoz', 'Roadster'),
    ('Perodua', 'Alza'),
    ('Perodua', 'Aruz'),
    ('Perodua', 'Axia'),
    ('Perodua', 'Bezza'),
    ('Perodua', 'Myvi'),
    ('Peugeot', '1007'),
    ('Peugeot', '104'),
    ('Peugeot', '106'),
    ('Peugeot', '107 3 Doors'),
    ('Peugeot', '107 5 Doors'),
    ('Peugeot', '108'),
    ('Peugeot', '2008'),
    ('Peugeot', '205'),
    ('Peugeot', '206 3 Doors'),
    ('Peugeot', '206 5 Doors'),
    ('Peugeot', '206 CC'),
    ('Peugeot', '206 SW'),
    ('Peugeot', '206 Sedan'),
    ('Peugeot', '206+ 3 Doors'),
    ('Peugeot', '206+ 5 Doors'),
    ('Peugeot', '207 3 Doors'),
    ('Peugeot', '207 5 Doors'),
    ('Peugeot', '207 CC'),
    ('Peugeot', '207 SW'),
    ('Peugeot', '208 3 doors'),
    ('Peugeot', '208 5 doors'),
    ('Peugeot', '208 GTI'),
    ('Peugeot', '208 XY'),
    ('Peugeot', '3008'),
    ('Peugeot', '301'),
    ('Peugeot', '306'),
    ('Peugeot', '307 3 Doors'),
    ('Peugeot', '307 5 Doors'),
    ('Peugeot', '307 CC'),
    ('Peugeot', '307 SW'),
    ('Peugeot', '307 Sedan'),
    ('Peugeot', '308 3 Doors'),
    ('Peugeot', '308 5 Doors'),
    ('Peugeot', '308 CC'),
    ('Peugeot', '308 SW'),
    ('Peugeot', '4007'),
    ('Peugeot', '4008'),
    ('Peugeot', '405'),
    ('Peugeot', '406'),
    ('Peugeot', '406 Break'),
    ('Peugeot', '406 Coupe'),
    ('Peugeot', '407'),
    ('Peugeot', '407 Coupe'),
    ('Peugeot', '407 SW'),
    ('Peugeot', '408 Fastback'),
    ('Peugeot', '408 Sedan'),
    ('Peugeot', '5008'),
    ('Peugeot', '504'),
    ('Peugeot', '505'),
    ('Peugeot', '508'),
    ('Peugeot', '508 RXH'),
    ('Peugeot', '508 SW'),
    ('Peugeot', '604'),
    ('Peugeot', '605'),
    ('Peugeot', '607'),
    ('Peugeot', '806'),
    ('Peugeot', '807'),
    ('Peugeot', 'Hoggar'),
    ('Peugeot', 'Landtrek'),
    ('Peugeot', 'Partner Combi'),
    ('Peugeot', 'Pick Up'),
    ('Peugeot', 'RCZ'),
    ('Peugeot', 'RCZ R'),
    ('Peugeot', 'RIFTER'),
    ('Peugeot', 'Tepee'),
    ('Peugeot', 'Traveller'),
    ('Peugeot', 'iOn'),
    ('Plymouth', 'ACCLAIM'),
    ('Plymouth', 'BARRACUDA'),
    ('Plymouth', 'BREEZE'),
    ('Plymouth', 'LASER'),
    ('Plymouth', 'NEON COUPE'),
    ('Plymouth', 'NEON SEDAN'),
    ('Plymouth', 'VOYAGER'),
    ('Plymouth', 'Valiant'),
    ('Pontiac', 'Aztek'),
    ('Pontiac', 'Bonneville'),
    ('Pontiac', 'Fiero'),
    ('Pontiac', 'Firebird'),
    ('Pontiac', 'G3'),
    ('Pontiac', 'G5'),
    ('Pontiac', 'G6'),
    ('Pontiac', 'G6 Convertible'),
    ('Pontiac', 'G6 Coupe'),
    ('Pontiac', 'G8'),
    ('Pontiac', 'GTO'),
    ('Pontiac', 'Grand Am'),
    ('Pontiac', 'Grand Prix'),
    ('Pontiac', 'Montana'),
    ('Pontiac', 'Solstice'),
    ('Pontiac', 'Sunfire Cabrio'),
    ('Pontiac', 'Sunfire Coupe'),
    ('Pontiac', 'Sunfire Sedan'),
    ('Pontiac', 'Torrent'),
    ('Pontiac', 'Trans Sport'),
    ('Pontiac', 'Vibe'),
    ('Porsche', '718 Boxster'),
    ('Porsche', '718 Boxster GTS'),
    ('Porsche', '718 Boxster S'),
    ('Porsche', '718 Cayman'),
    ('Porsche', '718 Cayman GT4'),
    ('Porsche', '718 Cayman GTS'),
    ('Porsche', '718 Cayman S'),
    ('Porsche', '718 Spyder'),
    ('Porsche', '911 Carrera'),
    ('Porsche', '911 Carrera 4'),
    ('Porsche', '911 Carrera 4 Cabriolet'),
    ('Porsche', '911 Carrera 4 GTS'),
    ('Porsche', '911 Carrera 4 GTS Cabriolet'),
    ('Porsche', '911 Carrera 4S'),
    ('Porsche', '911 Carrera 4S Cabriolet'),
    ('Porsche', '911 Carrera Cabriolet'),
    ('Porsche', '911 Carrera GTS'),
    ('Porsche', '911 Carrera GTS Cabriolet'),
    ('Porsche', '911 Carrera RS'),
    ('Porsche', '911 Carrera S'),
    ('Porsche', '911 Carrera S Cabriolet'),
    ('Porsche', '911 Carrera T'),
    ('Porsche', '911 GT2'),
    ('Porsche', '911 GT2 RS'),
    ('Porsche', '911 GT3'),
    ('Porsche', '911 GT3 RS'),
    ('Porsche', '911 R'),
    ('Porsche', '911 Sport Classic'),
    ('Porsche', '911 Targa'),
    ('Porsche', '911 Targa 4'),
    ('Porsche', '911 Targa 4 GTS'),
    ('Porsche', '911 Targa 4S'),
    ('Porsche', '911 Turbo'),
    ('Porsche', '911 Turbo Cabriolet'),
    ('Porsche', '911 Turbo S'),
    ('Porsche', '911 Turbo S Cabriolet'),
    ('Porsche', '918'),
    ('Porsche', '928'),
    ('Porsche', '928 GT'),
    ('Porsche', '928 GTS'),
    ('Porsche', '928 S'),
    ('Porsche', '944'),
    ('Porsche', '944 S'),
    ('Porsche', '944 Turbo'),
    ('Porsche', '959'),
    ('Porsche', '968'),
    ('Porsche', '968 Cabriolet'),
    ('Porsche', '968 Turbo S'),
    ('Porsche', 'Boxster'),
    ('Porsche', 'Boxster S'),
    ('Porsche', 'Boxster Spyder'),
    ('Porsche', 'Carrera GT'),
    ('Porsche', 'Cayenne'),
    ('Porsche', 'Cayenne Coupe'),
    ('Porsche', 'Cayenne Diesel'),
    ('Porsche', 'Cayenne Electric'),
    ('Porsche', 'Cayenne GTS'),
    ('Porsche', 'Cayenne GTS Coupe'),
    ('Porsche', 'Cayenne S'),
    ('Porsche', 'Cayenne S Diesel'),
    ('Porsche', 'Cayenne S E-Hybrid'),
    ('Porsche', 'Cayenne S Electric'),
    ('Porsche', 'Cayenne S Hybrid'),
    ('Porsche', 'Cayenne S TransSyberia'),
    ('Porsche', 'Cayenne Turbo'),
    ('Porsche', 'Cayenne Turbo Coupe'),
    ('Porsche', 'Cayenne Turbo E-Hybrid'),
    ('Porsche', 'Cayenne Turbo E-Hybrid Coupe'),
    ('Porsche', 'Cayenne Turbo S'),
    ('Porsche', 'Cayenne Turbo S E-Hybrid'),
    ('Porsche', 'Cayman'),
    ('Porsche', 'Cayman R'),
    ('Porsche', 'Cayman S'),
    ('Porsche', 'Macan'),
    ('Porsche', 'Macan 4 Electric'),
    ('Porsche', 'Macan GTS'),
    ('Porsche', 'Macan S'),
    ('Porsche', 'Macan S Diesel'),
    ('Porsche', 'Macan T'),
    ('Porsche', 'Macan Turbo'),
    ('Porsche', 'Macan Turbo Electric'),
    ('Porsche', 'Panamera'),
    ('Porsche', 'Panamera 4'),
    ('Porsche', 'Panamera 4 E-Hybrid'),
    ('Porsche', 'Panamera 4 E-Hybrid Sport Turismo'),
    ('Porsche', 'Panamera 4 Sport Turismo'),
    ('Porsche', 'Panamera 4S'),
    ('Porsche', 'Panamera 4S Diesel'),
    ('Porsche', 'Panamera 4S Diesel Sport Turismo'),
    ('Porsche', 'Panamera 4S E-Hybrid'),
    ('Porsche', 'Panamera 4S Sport Turismo'),
    ('Porsche', 'Panamera Diesel'),
    ('Porsche', 'Panamera GTS'),
    ('Porsche', 'Panamera GTS Sport Turismo'),
    ('Porsche', 'Panamera S'),
    ('Porsche', 'Panamera S E-Hybrid'),
    ('Porsche', 'Panamera S Hybrid'),
    ('Porsche', 'Panamera Turbo'),
    ('Porsche', 'Panamera Turbo E Hybrid'),
    ('Porsche', 'Panamera Turbo S'),
    ('Porsche', 'Panamera Turbo S E-Hybrid'),
    ('Porsche', 'Panamera Turbo S E-Hybrid Sport Turismo'),
    ('Porsche', 'Panamera Turbo S Sport Turismo'),
    ('Porsche', 'Panamera Turbo Sport Turismo'),
    ('Porsche', 'Speedster'),
    ('Porsche', 'Taycan'),
    ('Porsche', 'Taycan Cross Turismo'),
    ('Porsche', 'Taycan GTS'),
    ('Porsche', 'Taycan GTS Sport Turismo'),
    ('Porsche', 'Taycan Sport Turismo'),
    ('Porsche', 'Taycan Turbo'),
    ('Proton', 'Arena / Jumbuck'),
    ('Proton', 'Ertiga'),
    ('Proton', 'Exora'),
    ('Proton', 'Gen-2'),
    ('Proton', 'Inspira'),
    ('Proton', 'Iriz'),
    ('Proton', 'Perdana'),
    ('Proton', 'Persona'),
    ('Proton', 'Preve'),
    ('Proton', 'Saga'),
    ('Proton', 'Satria Neo'),
    ('Proton', 'Savvy'),
    ('Proton', 'Suprima S'),
    ('Proton', 'Waja / Impian'),
    ('Qoros', '3'),
    ('Qoros', '5'),
    ('Renault', '11'),
    ('Renault', '12'),
    ('Renault', '14'),
    ('Renault', '16'),
    ('Renault', '18'),
    ('Renault', '19'),
    ('Renault', '20'),
    ('Renault', '21'),
    ('Renault', '25'),
    ('Renault', '30'),
    ('Renault', '4 CV'),
    ('Renault', '4 E-Tech'),
    ('Renault', '5'),
    ('Renault', '5 E-Tech'),
    ('Renault', '8'),
    ('Renault', '9'),
    ('Renault', 'Alaskan'),
    ('Renault', 'Alpine'),
    ('Renault', 'Arkana'),
    ('Renault', 'Austral'),
    ('Renault', 'Avantime'),
    ('Renault', 'Boreal'),
    ('Renault', 'Captur'),
    ('Renault', 'City K-ZE'),
    ('Renault', 'Clio 3 Doors'),
    ('Renault', 'Clio 5 Doors'),
    ('Renault', 'Clio Estate'),
    ('Renault', 'Clio RS'),
    ('Renault', 'Clio Symbol / Thalia'),
    ('Renault', 'Duster OROCH'),
    ('Renault', 'Espace'),
    ('Renault', 'Filante'),
    ('Renault', 'Fluence'),
    ('Renault', 'Fuego'),
    ('Renault', 'Grand Kangoo'),
    ('Renault', 'Grand Modus'),
    ('Renault', 'Grand Scenic'),
    ('Renault', 'Kadjar'),
    ('Renault', 'Kangoo'),
    ('Renault', 'Kardian'),
    ('Renault', 'Kiger'),
    ('Renault', 'Koleos'),
    ('Renault', 'Kwid'),
    ('Renault', 'Laguna'),
    ('Renault', 'Laguna Coupe'),
    ('Renault', 'Laguna Estate'),
    ('Renault', 'Latitude'),
    ('Renault', 'Logan'),
    ('Renault', 'Megane 5 Doors'),
    ('Renault', 'Megane Cabriolet'),
    ('Renault', 'Megane Coupe'),
    ('Renault', 'Megane E-Tech'),
    ('Renault', 'Megane Estate'),
    ('Renault', 'Megane Sedan'),
    ('Renault', 'Modus'),
    ('Renault', 'Pulse'),
    ('Renault', 'Rafale'),
    ('Renault', 'SCENIC XMOD'),
    ('Renault', 'Safrane'),
    ('Renault', 'Sandero'),
    ('Renault', 'Sandero GT'),
    ('Renault', 'Scala'),
    ('Renault', 'Scenic'),
    ('Renault', 'Spider'),
    ('Renault', 'Symbioz'),
    ('Renault', 'Talisman'),
    ('Renault', 'Talisman Estate'),
    ('Renault', 'Triber'),
    ('Renault', 'Twingo'),
    ('Renault', 'Twingo RS'),
    ('Renault', 'Twizy'),
    ('Renault', 'Vel Satis'),
    ('Renault', 'Wind'),
    ('Renault', 'ZOE'),
    ('Rimac', 'Nevera'),
    ('Rivian', 'R1S'),
    ('Rivian', 'R1T'),
    ('Rivian', 'R2'),
    ('Rivian', 'R3'),
    ('Rivian', 'R3X'),
    ('Rolls-Royce', 'Arcadia'),
    ('Rolls-Royce', 'Camargue'),
    ('Rolls-Royce', 'Corniche'),
    ('Rolls-Royce', 'Cullinan'),
    ('Rolls-Royce', 'Dawn'),
    ('Rolls-Royce', 'Flying Spur'),
    ('Rolls-Royce', 'Ghost'),
    ('Rolls-Royce', 'La Rose Noire'),
    ('Rolls-Royce', 'Park Ward'),
    ('Rolls-Royce', 'Phantom'),
    ('Rolls-Royce', 'Silver Dawn'),
    ('Rolls-Royce', 'Silver Seraph'),
    ('Rolls-Royce', 'Silver Shadow'),
    ('Rolls-Royce', 'Silver Shadow Coupe'),
    ('Rolls-Royce', 'Silver Spirit'),
    ('Rolls-Royce', 'Silver Spur'),
    ('Rolls-Royce', 'Spectre'),
    ('Rolls-Royce', 'Wraith'),
    ('Rover', '100 Cabrio'),
    ('SEAT', 'Alhambra'),
    ('SEAT', 'Altea'),
    ('SEAT', 'Arona'),
    ('SEAT', 'Arosa'),
    ('SEAT', 'Ateca'),
    ('SEAT', 'Cordoba'),
    ('SEAT', 'Cordoba Cupra'),
    ('SEAT', 'Cordoba SX'),
    ('SEAT', 'Cordoba Vario'),
    ('SEAT', 'Exeo'),
    ('SEAT', 'Exeo ST'),
    ('SEAT', 'Ibiza'),
    ('SEAT', 'Ibiza 3 Doors'),
    ('SEAT', 'Ibiza 5 Doors'),
    ('SEAT', 'Ibiza Bocanegra'),
    ('SEAT', 'Ibiza Cupra'),
    ('SEAT', 'Ibiza FR'),
    ('SEAT', 'Ibiza ST'),
    ('SEAT', 'Leon'),
    ('SEAT', 'Leon Cupra'),
    ('SEAT', 'Leon Cupra R'),
    ('SEAT', 'Leon FR / Topsport'),
    ('SEAT', 'Leon SC'),
    ('SEAT', 'Leon ST Cupra'),
    ('SEAT', 'Leon ST Estate'),
    ('SEAT', 'Leon X-Perience'),
    ('SEAT', 'Malaga'),
    ('SEAT', 'Marbella'),
    ('SEAT', 'Mii'),
    ('SEAT', 'Tarraco'),
    ('SEAT', 'Toledo'),
    ('Saab', '9-2X'),
    ('Saab', '9-3 Aero'),
    ('Saab', '9-3 Convertible'),
    ('Saab', '9-3 Coupe'),
    ('Saab', '9-3 Sport Sedan'),
    ('Saab', '9-3 SportCombi'),
    ('Saab', '9-3X'),
    ('Saab', '9-5'),
    ('Saab', '9-5 SportCombi'),
    ('Saab', '9-7X'),
    ('Saab', '90'),
    ('Saab', '900'),
    ('Saab', '900 Cabrio'),
    ('Saab', '9000'),
    ('Saleen', 'S7'),
    ('Saleen', 'S7TT'),
    ('Samsung', 'SM 3'),
    ('Samsung', 'SM 5'),
    ('Samsung', 'SM 7'),
    ('Santana', '300 - 350'),
    ('Santana', 'PS 10 Pickup'),
    ('Santana', 'PS 10 Plus'),
    ('Santana', 'PS 10 Shortline'),
    ('Saturn', 'Astra'),
    ('Saturn', 'Aura'),
    ('Saturn', 'Ion Quad Coupe'),
    ('Saturn', 'Ion Sedan'),
    ('Saturn', 'Outlook'),
    ('Saturn', 'Relay'),
    ('Saturn', 'Sky'),
    ('Saturn', 'Vue'),
    ('Scion', 'FR-S'),
    ('Scion', 'iA'),
    ('Scion', 'iM'),
    ('Scion', 'iQ'),
    ('Scion', 'tC'),
    ('Scion', 'xA'),
    ('Scion', 'xB'),
    ('Scion', 'xD'),
    ('Scout Motors', 'Terra'),
    ('Scout Motors', 'Traveler'),
    ('Smart', '1'),
    ('Smart', '3'),
    ('Smart', '5'),
    ('Smart', 'Electric Drive'),
    ('Smart', 'Roadster'),
    ('Smart', 'Roadster Brabus'),
    ('Smart', 'Roadster Coupe'),
    ('Smart', 'Roadster Coupe Brabus'),
    ('Smart', 'crossblade'),
    ('Smart', 'forfour'),
    ('Smart', 'forfour Brabus'),
    ('Smart', 'fortwo'),
    ('Smart', 'fortwo Brabus'),
    ('Smart', 'fortwo Cabrio'),
    ('Smart', 'fortwo Cabrio Brabus'),
    ('Spyker', 'C12 LaTurbie'),
    ('Spyker', 'C8 Double 12 S')
ON CONFLICT (brand, model) DO NOTHING;

INSERT INTO car_models (brand, model) VALUES
    ('Spyker', 'C8 Laviolette'),
    ('Spyker', 'C8 Preliator'),
    ('Spyker', 'C8 Spyder'),
    ('SsangYong', 'Actyon'),
    ('SsangYong', 'Chairman'),
    ('SsangYong', 'Korando'),
    ('SsangYong', 'Kyron'),
    ('SsangYong', 'Musso'),
    ('SsangYong', 'Musso Sports'),
    ('SsangYong', 'Rexton'),
    ('SsangYong', 'Rodius'),
    ('SsangYong', 'Tivoli'),
    ('SsangYong', 'Tivoli XLV'),
    ('Subaru', '360'),
    ('Subaru', 'Ascent'),
    ('Subaru', 'BRZ'),
    ('Subaru', 'Baja'),
    ('Subaru', 'Crosstrek'),
    ('Subaru', 'Exiga Liberty'),
    ('Subaru', 'Forester'),
    ('Subaru', 'Getaway'),
    ('Subaru', 'Impreza'),
    ('Subaru', 'Impreza WRX STi'),
    ('Subaru', 'Justy'),
    ('Subaru', 'Legacy'),
    ('Subaru', 'Legacy Wagon'),
    ('Subaru', 'Levorg'),
    ('Subaru', 'Liberty'),
    ('Subaru', 'Mini Jumbo'),
    ('Subaru', 'Outback'),
    ('Subaru', 'Outback Wilderness'),
    ('Subaru', 'R1'),
    ('Subaru', 'R2'),
    ('Subaru', 'SVX'),
    ('Subaru', 'Solterra'),
    ('Subaru', 'Stella'),
    ('Subaru', 'Trezia'),
    ('Subaru', 'Tribeca'),
    ('Subaru', 'Uncharted'),
    ('Subaru', 'Vivio'),
    ('Subaru', 'WRX'),
    ('Subaru', 'XV'),
    ('Suzuki', 'APV'),
    ('Suzuki', 'Across'),
    ('Suzuki', 'Aerio / Liana Hatchback'),
    ('Suzuki', 'Aerio / Liana Sedan'),
    ('Suzuki', 'Alto'),
    ('Suzuki', 'Baleno'),
    ('Suzuki', 'Equator'),
    ('Suzuki', 'Ertiga'),
    ('Suzuki', 'Escudo / Grand Vitara 3 Doors'),
    ('Suzuki', 'Escudo / Grand Vitara 5 Doors'),
    ('Suzuki', 'Escudo / Vitara 3 Doors'),
    ('Suzuki', 'Forenza Sedan'),
    ('Suzuki', 'Forenza Wagon'),
    ('Suzuki', 'Ignis'),
    ('Suzuki', 'Jimny'),
    ('Suzuki', 'Kizashi'),
    ('Suzuki', 'Reno'),
    ('Suzuki', 'S-Cross'),
    ('Suzuki', 'SX4 Crossover'),
    ('Suzuki', 'SX4 Sedan'),
    ('Suzuki', 'Splash'),
    ('Suzuki', 'Swace'),
    ('Suzuki', 'Swift 3 Doors'),
    ('Suzuki', 'Swift 5 Doors'),
    ('Suzuki', 'Swift Cabriolet'),
    ('Suzuki', 'Swift Sedan'),
    ('Suzuki', 'Verona'),
    ('Suzuki', 'Vitara'),
    ('Suzuki', 'Wagon R'),
    ('Suzuki', 'X90'),
    ('Suzuki', 'XL7'),
    ('TVR', '"Wedge Series"'),
    ('TVR', 'Cerbera'),
    ('TVR', 'Chimaera'),
    ('TVR', 'Griffith'),
    ('TVR', 'Sagaris'),
    ('TVR', 'T350'),
    ('TVR', 'Tamora'),
    ('TVR', 'Tuscan'),
    ('TVR', 'Tuscan R/ T 440R/T 400R/ Typhon'),
    ('TVR', 'Tuscan S'),
    ('TVR', 'Tuscan S Convertible'),
    ('Tata Motors', 'Altroz'),
    ('Tata Motors', 'Aria'),
    ('Tata Motors', 'Harrier'),
    ('Tata Motors', 'Indica'),
    ('Tata Motors', 'Indigo'),
    ('Tata Motors', 'Indigo SW'),
    ('Tata Motors', 'Nano'),
    ('Tata Motors', 'Nexon'),
    ('Tata Motors', 'Safari'),
    ('Tata Motors', 'Sumo'),
    ('Tata Motors', 'Telcoline Double Cab'),
    ('Tesla', 'Cybertruck'),
    ('Tesla', 'Model 3'),
    ('Tesla', 'Model S'),
    ('Tesla', 'Model X'),
    ('Tesla', 'Model Y'),
    ('Tesla', 'Roadster'),
    ('Togg', 'T10F'),
    ('Togg', 'T10X'),
    ('Toyota', '4Runner'),
    ('Toyota', 'Agya'),
    ('Toyota', 'Alphard'),
    ('Toyota', 'Aqua'),
    ('Toyota', 'Aurion'),
    ('Toyota', 'Auris 3 Doors'),
    ('Toyota', 'Auris 5 Doors'),
    ('Toyota', 'Auris Touring'),
    ('Toyota', 'Avalon'),
    ('Toyota', 'Avensis'),
    ('Toyota', 'Avensis Liftback'),
    ('Toyota', 'Avensis Verso'),
    ('Toyota', 'Avensis Wagon'),
    ('Toyota', 'Aygo 3 Doors'),
    ('Toyota', 'Aygo 5 Doors'),
    ('Toyota', 'Aygo X'),
    ('Toyota', 'C-HR'),
    ('Toyota', 'Camry'),
    ('Toyota', 'Celica'),
    ('Toyota', 'Celica Convertible'),
    ('Toyota', 'Century SUV'),
    ('Toyota', 'Century Sedan'),
    ('Toyota', 'Corolla'),
    ('Toyota', 'Corolla (US)'),
    ('Toyota', 'Corolla 3 Doors'),
    ('Toyota', 'Corolla 5 Doors'),
    ('Toyota', 'Corolla Cross'),
    ('Toyota', 'Corolla Cross (US)'),
    ('Toyota', 'Corolla Liftback'),
    ('Toyota', 'Corolla Sedan'),
    ('Toyota', 'Corolla Touring'),
    ('Toyota', 'Corolla Verso'),
    ('Toyota', 'Corolla Wagon'),
    ('Toyota', 'Crown'),
    ('Toyota', 'Crown Estate'),
    ('Toyota', 'Crown SUV'),
    ('Toyota', 'Etios'),
    ('Toyota', 'Etios Liva'),
    ('Toyota', 'FJ Cruiser'),
    ('Toyota', 'Fortuner'),
    ('Toyota', 'GR 86'),
    ('Toyota', 'GR Corolla'),
    ('Toyota', 'GR Supra'),
    ('Toyota', 'GR Yaris'),
    ('Toyota', 'GT 86'),
    ('Toyota', 'Grand Highlander'),
    ('Toyota', 'Harrier'),
    ('Toyota', 'Highlander / Kluger'),
    ('Toyota', 'Hilux'),
    ('Toyota', 'Hilux Double Cab'),
    ('Toyota', 'Hilux Extra Cab'),
    ('Toyota', 'Hilux Single Cab'),
    ('Toyota', 'Innova'),
    ('Toyota', 'Land Cruiser / Prado'),
    ('Toyota', 'Land Cruiser V8 and predecessors'),
    ('Toyota', 'MR2'),
    ('Toyota', 'MR2 Cabriolet'),
    ('Toyota', 'Matrix'),
    ('Toyota', 'Mirai'),
    ('Toyota', 'Paseo'),
    ('Toyota', 'Picnic'),
    ('Toyota', 'Previa / Estima'),
    ('Toyota', 'Prius'),
    ('Toyota', 'Prius C (Aqua)'),
    ('Toyota', 'Prius Prime'),
    ('Toyota', 'Prius v/Prius+'),
    ('Toyota', 'RAV4 3 Doors'),
    ('Toyota', 'RAV4 5 Doors'),
    ('Toyota', 'Rukus'),
    ('Toyota', 'Sequoia'),
    ('Toyota', 'Sienna'),
    ('Toyota', 'Solara Convertible'),
    ('Toyota', 'Starlet 3 Doors'),
    ('Toyota', 'Starlet 5 Doors'),
    ('Toyota', 'Supra'),
    ('Toyota', 'Tacoma'),
    ('Toyota', 'Tundra'),
    ('Toyota', 'Urban Cruiser'),
    ('Toyota', 'VERSO-S'),
    ('Toyota', 'Venza'),
    ('Toyota', 'Verso'),
    ('Toyota', 'Vios'),
    ('Toyota', 'Yaris 3 Doors'),
    ('Toyota', 'Yaris 5 Doors'),
    ('Toyota', 'Yaris Cross'),
    ('Toyota', 'Yaris Hatchback'),
    ('Toyota', 'Yaris Sedan'),
    ('Toyota', 'Yaris TS 3 Doors'),
    ('Toyota', 'Yaris TS 5 Doors'),
    ('Toyota', 'Yaris Verso'),
    ('Toyota', 'bZ (US)'),
    ('Toyota', 'bZ4X'),
    ('Toyota', 'bZ4X Touring'),
    ('Toyota', 'iQ'),
    ('Vauxhall', 'Agila'),
    ('Vauxhall', 'Antara'),
    ('Vauxhall', 'Astra Estate'),
    ('Vauxhall', 'Astra Hatchback'),
    ('Vauxhall', 'Astra Sport Hatch'),
    ('Vauxhall', 'Astra Twin Top'),
    ('Vauxhall', 'Astra VXR'),
    ('Vauxhall', 'Corsa 3 Doors'),
    ('Vauxhall', 'Corsa 5 Doors'),
    ('Vauxhall', 'Corsa VXR'),
    ('Vauxhall', 'Crossland X'),
    ('Vauxhall', 'Grandland'),
    ('Vauxhall', 'Insignia Country Tourer'),
    ('Vauxhall', 'Insignia Hatchback'),
    ('Vauxhall', 'Insignia Sedan'),
    ('Vauxhall', 'Insignia Sports Tourer'),
    ('Vauxhall', 'Insignia VXR Sedan'),
    ('Vauxhall', 'Insignia VXR Sports Tourer'),
    ('Vauxhall', 'Meriva'),
    ('Vauxhall', 'Meriva VXR'),
    ('Vauxhall', 'Mokka'),
    ('Vauxhall', 'Mokka X'),
    ('Vauxhall', 'Monaro'),
    ('Vauxhall', 'Monaro VXR'),
    ('Vauxhall', 'Signum'),
    ('Vauxhall', 'Tigra Twin Top'),
    ('Vauxhall', 'VX 220'),
    ('Vauxhall', 'VXR8'),
    ('Vauxhall', 'Vectra Estate'),
    ('Vauxhall', 'Vectra Estate VXR'),
    ('Vauxhall', 'Vectra Hatchback'),
    ('Vauxhall', 'Vectra Saloon'),
    ('Vauxhall', 'Vectra VXR'),
    ('Vauxhall', 'Viva'),
    ('Vauxhall', 'Zafira'),
    ('Vauxhall', 'Zafira VXR'),
    ('Volkswagen', 'Amarok'),
    ('Volkswagen', 'Ameo'),
    ('Volkswagen', 'Arteon'),
    ('Volkswagen', 'Arteon Shooting Brake'),
    ('Volkswagen', 'Atlas'),
    ('Volkswagen', 'Atlas Cross Sport'),
    ('Volkswagen', 'Beetle'),
    ('Volkswagen', 'Beetle Cabrio'),
    ('Volkswagen', 'CC'),
    ('Volkswagen', 'Caddy'),
    ('Volkswagen', 'Corrado'),
    ('Volkswagen', 'Cross UP!'),
    ('Volkswagen', 'Derby'),
    ('Volkswagen', 'Eos'),
    ('Volkswagen', 'Fox'),
    ('Volkswagen', 'Gol'),
    ('Volkswagen', 'Golf 3 Doors'),
    ('Volkswagen', 'Golf 5 Doors'),
    ('Volkswagen', 'Golf Alltrack'),
    ('Volkswagen', 'Golf Cabrio'),
    ('Volkswagen', 'Golf GTD Variant'),
    ('Volkswagen', 'Golf GTI / GTD / GTE'),
    ('Volkswagen', 'Golf GTI cabrio'),
    ('Volkswagen', 'Golf Plus'),
    ('Volkswagen', 'Golf R'),
    ('Volkswagen', 'Golf R Cabrio'),
    ('Volkswagen', 'Golf R Variant'),
    ('Volkswagen', 'Golf Sportsvan'),
    ('Volkswagen', 'Golf Variant'),
    ('Volkswagen', 'ID. Buzz'),
    ('Volkswagen', 'ID.3'),
    ('Volkswagen', 'ID.3 GTX'),
    ('Volkswagen', 'ID.4'),
    ('Volkswagen', 'ID.5'),
    ('Volkswagen', 'ID.5 GTX'),
    ('Volkswagen', 'ID.7'),
    ('Volkswagen', 'ID.7 GTX'),
    ('Volkswagen', 'ID.7 GTX Tourer'),
    ('Volkswagen', 'ID.7 Tourer'),
    ('Volkswagen', 'Jetta / Vento / Bora'),
    ('Volkswagen', 'Jetta GLI'),
    ('Volkswagen', 'Lavida (China)'),
    ('Volkswagen', 'Lupo'),
    ('Volkswagen', 'Multivan'),
    ('Volkswagen', 'Nivus'),
    ('Volkswagen', 'Passat'),
    ('Volkswagen', 'Passat 3 Doors'),
    ('Volkswagen', 'Passat Alltrack'),
    ('Volkswagen', 'Passat GTE'),
    ('Volkswagen', 'Passat Hatchback'),
    ('Volkswagen', 'Passat R'),
    ('Volkswagen', 'Passat Variant'),
    ('Volkswagen', 'Passat Variant GTE'),
    ('Volkswagen', 'Phaeton'),
    ('Volkswagen', 'Pointer'),
    ('Volkswagen', 'Polo 3 Doors'),
    ('Volkswagen', 'Polo 5 Doors'),
    ('Volkswagen', 'Polo BlueGT'),
    ('Volkswagen', 'Polo Coupe'),
    ('Volkswagen', 'Polo GTI'),
    ('Volkswagen', 'Polo Sedan'),
    ('Volkswagen', 'Polo Variant'),
    ('Volkswagen', 'Routan'),
    ('Volkswagen', 'Santana'),
    ('Volkswagen', 'Scirocco'),
    ('Volkswagen', 'Scirocco R'),
    ('Volkswagen', 'Sharan'),
    ('Volkswagen', 'T-Cross'),
    ('Volkswagen', 'T-Roc'),
    ('Volkswagen', 'T-Roc Cabriolet'),
    ('Volkswagen', 'T-Roc R'),
    ('Volkswagen', 'Taigo'),
    ('Volkswagen', 'Taos'),
    ('Volkswagen', 'Tayron'),
    ('Volkswagen', 'Tiguan'),
    ('Volkswagen', 'Tiguan (US)'),
    ('Volkswagen', 'Tiguan Allspace'),
    ('Volkswagen', 'Touareg'),
    ('Volkswagen', 'Touareg R'),
    ('Volkswagen', 'Touran'),
    ('Volkswagen', 'Transporter Kombi'),
    ('Volkswagen', 'Vento'),
    ('Volkswagen', 'XL1'),
    ('Volkswagen', 'e-Golf'),
    ('Volkswagen', 'e-UP!'),
    ('Volkswagen', 'up!'),
    ('Volkswagen', 'up! GTI'),
    ('Volvo', '142'),
    ('Volvo', '144'),
    ('Volvo', '145'),
    ('Volvo', '244'),
    ('Volvo', '245'),
    ('Volvo', '262'),
    ('Volvo', '264'),
    ('Volvo', '265'),
    ('Volvo', '343'),
    ('Volvo', '345'),
    ('Volvo', '440'),
    ('Volvo', '460'),
    ('Volvo', '480'),
    ('Volvo', '66'),
    ('Volvo', '760'),
    ('Volvo', '760 Estate'),
    ('Volvo', '780'),
    ('Volvo', '850'),
    ('Volvo', '850 Estate'),
    ('Volvo', '940'),
    ('Volvo', '940 Estate'),
    ('Volvo', '960'),
    ('Volvo', '960 Estate'),
    ('Volvo', 'C30'),
    ('Volvo', 'C40'),
    ('Volvo', 'C70'),
    ('Volvo', 'C70 Convertible'),
    ('Volvo', 'C70 Coupe'),
    ('Volvo', 'EM90'),
    ('Volvo', 'ES90'),
    ('Volvo', 'EX30'),
    ('Volvo', 'EX30 Cross Country'),
    ('Volvo', 'EX60'),
    ('Volvo', 'EX60 Cross Country'),
    ('Volvo', 'EX90'),
    ('Volvo', 'P1800'),
    ('Volvo', 'S40'),
    ('Volvo', 'S60'),
    ('Volvo', 'S60 Cross Country'),
    ('Volvo', 'S60 Polestar'),
    ('Volvo', 'S70'),
    ('Volvo', 'S80'),
    ('Volvo', 'S90'),
    ('Volvo', 'V40'),
    ('Volvo', 'V40 Cross Country'),
    ('Volvo', 'V50'),
    ('Volvo', 'V60'),
    ('Volvo', 'V60 Cross Country'),
    ('Volvo', 'V60 Polestar'),
    ('Volvo', 'V70'),
    ('Volvo', 'V90'),
    ('Volvo', 'V90 Cross Country'),
    ('Volvo', 'XC40'),
    ('Volvo', 'XC60'),
    ('Volvo', 'XC60 Polestar'),
    ('Volvo', 'XC70'),
    ('Volvo', 'XC90'),
    ('Wiesmann', 'GT MF4'),
    ('Wiesmann', 'GT MF4-CS'),
    ('Wiesmann', 'GT MF4-S'),
    ('Wiesmann', 'GT MF5'),
    ('Wiesmann', 'MF4 Roadster'),
    ('Wiesmann', 'MF4-S Roadster'),
    ('Wiesmann', 'MF5 Roadster'),
    ('Zender', 'Escape 6'),
    ('Zender', 'Fact 4 BiTurbo'),
    ('Zender', 'Fact 4 Spider'),
    ('Zender', 'Progetto 5'),
    ('Zender', 'Straight 8'),
    ('Zender', 'Thirty 7'),
    ('Škoda', '100 series'),
    ('Škoda', '860'),
    ('Škoda', 'Citigo'),
    ('Škoda', 'Elroq'),
    ('Škoda', 'Elroq RS'),
    ('Škoda', 'Enyaq'),
    ('Škoda', 'Enyaq Coupe'),
    ('Škoda', 'Enyaq Coupe RS'),
    ('Škoda', 'Enyaq RS'),
    ('Škoda', 'Fabia'),
    ('Škoda', 'Fabia Combi'),
    ('Škoda', 'Fabia Combi RS'),
    ('Škoda', 'Fabia RS'),
    ('Škoda', 'Fabia Sedan'),
    ('Škoda', 'Favorit'),
    ('Škoda', 'Favorit Estate'),
    ('Škoda', 'Felicia'),
    ('Škoda', 'Felicia Combi'),
    ('Škoda', 'Kamiq'),
    ('Škoda', 'Karoq'),
    ('Škoda', 'Kodiaq'),
    ('Škoda', 'Kodiaq RS'),
    ('Škoda', 'Kushaq'),
    ('Škoda', 'Kylaq'),
    ('Škoda', 'Octavia'),
    ('Škoda', 'Octavia Combi'),
    ('Škoda', 'Octavia Combi 4x4'),
    ('Škoda', 'Octavia Combi RS'),
    ('Škoda', 'Octavia RS'),
    ('Škoda', 'Octavia Scout'),
    ('Škoda', 'Rapid'),
    ('Škoda', 'Rapid Spaceback'),
    ('Škoda', 'Roomster'),
    ('Škoda', 'Scala'),
    ('Škoda', 'Slavia'),
    ('Škoda', 'Superb'),
    ('Škoda', 'Superb Combi / Scout'),
    ('Škoda', 'Yeti')
ON CONFLICT (brand, model) DO NOTHING;
