ktor:
  application:
    modules:
      - com.carspotter.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0

#database:
#  development:
#    url: ${DEV_DB_URL}
#    user: ${DEV_USER}
#    password: ${DEV_PASSWORD}
#
#  testing:
#    url: ${TEST_DB_URL}
#    user: ${TEST_DB_USER}
#    password: ${TEST_DB_PASSWORD}
#
#  production:
#    url: ${PROD_DB_URL}
#    user: ${PROD_USER}
#    password: ${PROD_PASSWORD}