ktor:
  application:
    modules:
      - com.carspotter.ApplicationKt.module
  deployment:
    port: 9291
    host: 0.0.0.0
  environment: development

database:
  development:
    url: "jdbc:postgresql://localhost:5432/CarSpotter"
    user: "postgres"
    password: "Andrei2003."

  testing:
    url: "jdbc:postgresql://localhost:5432/test_postgres"
    user: "postgres"
    password: "Andrei2003."