ktor:
  application:
    modules:
      - com.carspotter.ApplicationKt.module
  deployment:
    port: ${PORT:9291}
    host: 0.0.0.0
  environment: ${KTOR_ENV:development}

database:
  development:
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    password: "Andrei2003."
  production:
    url: ${DATABASE_URL}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  testing:
    url: ${TEST_DB_URL}
    user: ${TEST_DB_USER}
    password: ${TEST_DB_PASSWORD}