#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $TEST_DB_USER WITH PASSWORD '$TEST_DB_PASSWORD';
    CREATE DATABASE $TEST_DB OWNER $TEST_DB_USER;
    CREATE USER $PROD_USER WITH PASSWORD '$PROD_PASSWORD';
    CREATE DATABASE $PROD_DB OWNER $PROD_USER;
EOSQL